-- supabase/seed/0001_content_batches.sql
-- ⛔ GENERATED by scripts/build-ingest-sql.mjs — do not edit by hand.
--    Regenerate with `npm run build:ingest`. Apply exactly like a migration.
--
-- lot 343 · inspect 343 · accept up to 2 · basis: full
-- lot of 343 is below 501 and we hold no sample-size row beneath that boundary, so every item is inspected rather than a sample size invented (R-014)
--
-- Every row below was re-gated by lib/core/contentSchema.ts (R-014) before emission.
-- Scoring material (sense_examples / sense_items / sense_distractors) is NOT written here.
-- Re-runnable: words upsert on (headword, pos); senses do nothing on (word_id, sense_index).

begin;

-- --------------------------------------------------------------------------
-- batch-2026-08-07.jsonl — 45 of 45 rows pass the gate
-- --------------------------------------------------------------------------
with run as (
  insert into public.generation_runs (model, prompt_version, requested, accepted, rejected, notes)
  values ('claude-opus-5', 'content-agent/2026-08-07', 45, 45, 0, 'batch-2026-08-07.jsonl')
  returning id
), incoming (headword, pos, n_letters, n_syllables, is_function_word, sense_index,
            definition_en, translation_he, cefr_level, translation_confidence,
            he_interference_note, he_one_to_many_group, needs_human_review) as (
  values
    ('work', 'noun', 4, 1, false, 1, 'the job a person does to earn money', 'עבודה', 'A1', 'high', null, 'עבודה = work / job', false),
    ('give', 'verb', 4, 1, false, 1, 'to hand something to someone', 'לתת', 'A1', 'high', null, null, false),
    ('right', 'adjective', 5, 1, false, 1, 'correct, without a mistake', 'נכון', 'A1', 'high', 'בעברית אומרים אתה צודק בפועל, ולכן לומדים כותבים you right בלי is או are.', 'נכון = right / correct / true', false),
    ('mean', 'verb', 4, 1, false, 1, 'to want to say something in particular', 'להתכוון', 'B1', 'high', null, null, false),
    ('company', 'noun', 7, 3, false, 1, 'a business that sells goods or services', 'חברה', 'A2', 'high', 'חברה מכסה גם company וגם friendship, ולכן לומדים כותבים my company כשהכוונה my friend.', 'חברה = company / society / friendship', false),
    ('tell', 'verb', 4, 1, false, 1, 'to give information to someone by speaking', 'לספר', 'A1', 'high', 'בעברית לספר דורש מילת יחס, ולכן לומדים כותבים tell to me במקום tell me.', null, false),
    ('place', 'noun', 5, 1, false, 1, 'an area or position where something is', 'מקום', 'A1', 'high', null, null, false),
    ('change', 'verb', 6, 1, false, 1, 'to make something different', 'לשנות', 'A2', 'high', null, null, false),
    ('problem', 'noun', 7, 2, false, 1, 'something difficult that must be dealt with', 'בעיה', 'A2', 'high', null, null, false),
    ('leave', 'verb', 5, 1, false, 1, 'to go away from a place', 'לעזוב', 'A1', 'high', 'leave מכסה גם לעזוב וגם להשאיר; לומדים בוחרים לפי לעזוב ומפספסים I left my bag at home.', null, false),
    ('meet', 'verb', 4, 1, false, 1, 'to come together with someone in the same place', 'לפגוש', 'A1', 'high', null, null, false),
    ('ask', 'verb', 3, 1, false, 1, 'to say something as a question', 'לשאול', 'A1', 'high', 'ask מכסה גם לשאול וגם לבקש, ולכן לומדים מתרגמים ask לשאלה בלבד ומפספסים ask for help.', null, false),
    ('school', 'noun', 6, 1, false, 1, 'a place where children go to learn', 'בית ספר', 'A1', 'high', null, null, false),
    ('different', 'adjective', 9, 3, false, 1, 'not the same as something else', 'שונה', 'A2', 'high', null, null, false),
    ('late', 'adjective', 4, 1, false, 1, 'arriving after the expected time', 'מאוחר', 'A1', 'high', null, null, false),
    ('study', 'verb', 5, 2, false, 1, 'to spend time learning about a subject', 'ללמוד', 'A1', 'high', 'ללמוד מכסה study ו-learn; לומדים כותבים I studied English כשהכוונה לרכישת ידע ולא לעיסוק בלימוד.', 'ללמוד = study / learn', false),
    ('report', 'noun', 6, 2, false, 1, 'a written or spoken account of something', 'דוח', 'B1', 'high', null, null, false),
    ('group', 'noun', 5, 1, false, 1, 'a number of people or things that are together', 'קבוצה', 'A2', 'high', null, null, false),
    ('seem', 'verb', 4, 1, false, 1, 'to appear to be something', 'להיראות', 'B1', 'high', null, 'להיראות = seem / look / appear', false),
    ('keep', 'verb', 4, 1, false, 1, 'to continue to have something', 'לשמור', 'A2', 'high', null, null, false),
    ('follow', 'verb', 6, 2, false, 1, 'to go behind someone and go where they go', 'לעקוב', 'A2', 'high', null, null, false),
    ('important', 'adjective', 9, 3, false, 1, 'having a great effect or value', 'חשוב', 'A2', 'high', null, null, false),
    ('friend', 'noun', 6, 1, false, 1, 'someone you like and know well', 'חבר', 'A1', 'high', 'חבר מכסה friend ו-member, ולכן לומדים כותבים he is my friend in the team במקום member.', 'חבר = friend / member / boyfriend', false),
    ('small', 'adjective', 5, 1, false, 1, 'little in size or amount', 'קטן', 'A1', 'high', null, null, false),
    ('turn', 'verb', 4, 1, false, 1, 'to move so that you face another direction', 'לפנות', 'A2', 'high', null, null, false),
    ('begin', 'verb', 5, 2, false, 1, 'to start doing something', 'להתחיל', 'A2', 'high', null, null, false),
    ('early', 'adjective', 5, 2, false, 1, 'happening before the usual time', 'מוקדם', 'A2', 'high', null, null, false),
    ('bring', 'verb', 5, 1, false, 1, 'to take something to the place where you are', 'להביא', 'A2', 'high', 'להביא מכסה bring ו-take, ולכן לומדים כותבים bring it there במקום take it there.', null, false),
    ('area', 'noun', 4, 3, false, 1, 'a part of a place, town or country', 'אזור', 'B1', 'high', null, null, false),
    ('business', 'noun', 8, 2, false, 1, 'the work of buying and selling things', 'עסק', 'B1', 'high', null, null, false),
    ('fact', 'noun', 4, 1, false, 1, 'something that is true and can be shown to be true', 'עובדה', 'B1', 'high', null, null, false),
    ('large', 'adjective', 5, 1, false, 1, 'big in size or amount', 'גדול', 'A2', 'high', null, null, false),
    ('increase', 'verb', 8, 2, false, 1, 'to become greater in number, amount or size', 'לגדול', 'B1', 'high', null, null, false),
    ('open', 'verb', 4, 2, false, 1, 'to move something so that it is no longer closed', 'לפתוח', 'A1', 'high', null, null, false),
    ('hold', 'verb', 4, 1, false, 1, 'to have something in your hand', 'להחזיק', 'A2', 'high', null, null, false),
    ('job', 'noun', 3, 1, false, 1, 'the work a person does regularly for money', 'עבודה', 'A1', 'high', null, 'עבודה = work / job', false),
    ('believe', 'verb', 7, 2, false, 1, 'to think that something is true', 'להאמין', 'B1', 'high', null, null, false),
    ('plan', 'noun', 4, 1, false, 1, 'an idea about what you will do later', 'תוכנית', 'A2', 'high', null, null, false),
    ('close', 'verb', 5, 1, false, 1, 'to move something so that it is not open', 'לסגור', 'A1', 'high', null, null, false),
    ('hope', 'verb', 4, 1, false, 1, 'to want something to happen and think it may happen', 'לקוות', 'A2', 'high', null, null, false),
    ('cost', 'noun', 4, 1, false, 1, 'the amount of money needed to buy something', 'עלות', 'B1', 'high', null, null, false),
    ('understand', 'verb', 10, 3, false, 1, 'to know the meaning of something', 'להבין', 'B1', 'high', null, null, false),
    ('spend', 'verb', 5, 1, false, 1, 'to use money to buy things', 'להוציא', 'B1', 'medium', null, null, false),
    ('idea', 'noun', 4, 3, false, 1, 'a thought or plan in your mind', 'רעיון', 'A2', 'high', null, null, false),
    ('reason', 'noun', 6, 2, false, 1, 'why something happens or why someone does something', 'סיבה', 'B1', 'high', null, null, false)
), w as (
  insert into public.words (headword, pos, origin, n_letters, n_syllables, is_function_word)
  select distinct on (headword, pos) headword, pos, 'generated', n_letters, n_syllables, is_function_word
  from incoming
  order by headword, pos
  on conflict (headword, pos) do update set headword = excluded.headword
  returning id, headword, pos
)
insert into public.senses (word_id, sense_index, definition_en, translation_he, cefr_level,
                           translation_confidence, he_interference_note, he_one_to_many_group,
                           generation_run_id, needs_human_review)
select w.id, i.sense_index, i.definition_en, i.translation_he, i.cefr_level,
       i.translation_confidence, i.he_interference_note, i.he_one_to_many_group,
       run.id, i.needs_human_review
from incoming i
join w on w.headword = i.headword and w.pos = i.pos
cross join run
on conflict (word_id, sense_index) do nothing;

-- --------------------------------------------------------------------------
-- batch-2026-08-08.jsonl — 55 of 55 rows pass the gate
-- --------------------------------------------------------------------------
with run as (
  insert into public.generation_runs (model, prompt_version, requested, accepted, rejected, notes)
  values ('claude-opus-5', 'content-agent/2026-08-08', 45, 55, 0, 'batch-2026-08-08.jsonl')
  returning id
), incoming (headword, pos, n_letters, n_syllables, is_function_word, sense_index,
            definition_en, translation_he, cefr_level, translation_confidence,
            he_interference_note, he_one_to_many_group, needs_human_review) as (
  values
    ('then', 'adverb', 4, 1, true, 1, 'at that particular time in the past or future', 'אז', 'A1', 'high', 'בעברית ''אז'' מציין גם זמן וגם מסקנה, ולכן דובר עברית כותב then במקום so.', 'אז = then · so', false),
    ('then', 'adverb', 4, 1, true, 2, 'after that; next in a sequence of actions', 'אחרכך', 'A1', 'high', null, null, false),
    ('now', 'adverb', 3, 1, true, 1, 'at the present time or moment', 'עכשיו', 'A1', 'high', 'דובר עברית מחליף בכתיב בין now ל-know כי ה-k אינה נשמעת.', null, false),
    ('also', 'adverb', 4, 2, true, 1, 'in addition; as well as something already mentioned', 'גם', 'A1', 'high', 'העברית מציבה ''גם'' לפני המילה, ולכן דובר עברית כותב also I like it במקום I also like it.', 'גם = also · too · as well', false),
    ('than', 'conjunction', 4, 1, true, 1, 'used after a comparative word to introduce the second thing compared', 'מאשר', 'A1', 'high', 'בעברית ההשוואה נעשית באות ''מ'' מחוברת (גדול ממנו), ולכן דובר עברית משמיט את than או מחליף אותה ב-from.', null, false),
    ('him', 'pronoun', 3, 1, true, 1, 'the form of he used as the object of a verb or preposition', 'אותו', 'A1', 'high', 'בעברית ''אותו'' משמש גם לאדם וגם לחפץ, ולכן דובר עברית אומר him על עצם דומם במקום it.', 'אותו = him · it', false),
    ('into', 'preposition', 4, 2, true, 1, 'moving to a position inside something', 'לתוך', 'A1', 'high', 'בעברית אות אחת (''ב'') מכסה גם מקום סטטי וגם תנועה פנימה, ולכן דובר עברית כותב in במקום into אחרי פועל תנועה.', 'ב = in · into · at', false),
    ('only', 'adverb', 4, 2, true, 1, 'no more than; nothing other than the thing mentioned', 'רק', 'A1', 'high', 'בעברית ''רק'' עומד לפני המילה שהוא מגביל, ודובר עברית מציב only בתחילת המשפט גם כשהוא מגביל את המושא.', 'רק = only · just', false),
    ('only', 'adjective', 4, 2, false, 2, 'being the single one of its kind in a group', 'יחיד', 'A2', 'high', null, null, false),
    ('want', 'verb', 4, 1, false, 1, 'to feel that you would like to have or do something', 'לרצות', 'A1', 'high', 'דובר עברית מחליף בכתיב בין want לבין wait, ומשתמש ב-want גם לתיאור צורך שדורש need.', null, false),
    ('look', 'verb', 4, 1, false, 1, 'to turn your eyes towards something in order to see it', 'להסתכל', 'A1', 'high', 'בעברית אומרים ''להסתכל על'', ולכן דובר עברית מעתיק את מילת היחס וכותב look on במקום look at.', 'להסתכל = look · see · watch', false),
    ('look', 'verb', 4, 1, false, 2, 'to seem or appear to be a particular way', 'להיראות', 'A2', 'high', 'בעברית משתמשים ב''נראה כמו'', ולכן דובר עברית מוסיף like לפני שם תואר: look like tired במקום look tired.', 'להיראות = look · seem · appear', false),
    ('these', 'determiner', 5, 1, true, 1, 'used for people or things near you when there is more than one', 'אלה', 'A1', 'high', 'בעברית ''אלה'' אינו מבחין בין קרוב לרחוק, ולכן דובר עברית מחליף these ב-those.', 'אלה = these · those', false),
    ('its', 'determiner', 3, 1, true, 1, 'belonging to or connected with a thing or animal already mentioned', 'שלו', 'A2', 'high', 'בעברית ''שלו'' משמש גם לאדם וגם לחפץ, ולכן דובר עברית כותב his על חפץ, וגם מוסיף גרש ומקבל it''s שפירושו it is.', 'שלו = his · its', false),
    ('new', 'adjective', 3, 1, false, 1, 'made or bought a short time ago; not existing before', 'חדש', 'A1', 'high', 'new ו-knew נשמעות זהה, ודובר עברית שאינו מבחין ביניהן בכתיב מחליף אותן.', null, false),
    ('first', 'adjective', 5, 1, false, 1, 'coming before all others in order, time or importance', 'ראשון', 'A1', 'high', null, null, false),
    ('first', 'adverb', 5, 1, true, 2, 'before doing anything else', 'קודם', 'A2', 'high', null, null, false),
    ('way', 'noun', 3, 1, false, 1, 'a road or path that you follow to reach a place', 'דרך', 'A1', 'high', 'בעברית ''דרך'' היא גם נתיב וגם מילת יחס, ולכן דובר עברית משתמש ב-way במקום through.', 'דרך = way · road · through', false),
    ('way', 'noun', 3, 1, false, 2, 'a method or manner of doing something', 'אופן', 'A2', 'high', null, null, false),
    ('thing', 'noun', 5, 1, false, 1, 'an object, fact or event that you do not name exactly', 'דבר', 'A1', 'high', null, 'דבר = thing · word · matter', false),
    ('any', 'determiner', 3, 2, true, 1, 'some amount or number of something, used in questions and negatives', 'כלשהו', 'A1', 'medium', 'בעברית אין הבחנה בין any ל-some, ולכן דובר עברית משתמש ב-some בשאלות ובשלילה.', 'קצת = any · some', false),
    ('over', 'preposition', 4, 2, true, 1, 'above something, or covering it from above', 'מעל', 'A1', 'high', null, 'מעל = over · above', false),
    ('over', 'adjective', 4, 2, false, 2, 'finished or no longer happening', 'נגמר', 'A2', 'high', null, null, false),
    ('after', 'preposition', 5, 2, true, 1, 'later than a particular time or event', 'אחרי', 'A1', 'high', 'בעברית ''אחרי'' מציין גם זמן וגם מקום, ולכן דובר עברית כותב after במקום behind.', 'אחרי = after · behind', false),
    ('find', 'verb', 4, 1, false, 1, 'to discover something, either by looking for it or by chance', 'למצוא', 'A1', 'high', 'דובר עברית מבלבל בין found כצורת העבר של find לבין הפועל found שפירושו ''להקים''.', null, false),
    ('day', 'noun', 3, 1, false, 1, 'a period of one whole date, or the time when it is light', 'יום', 'A1', 'high', null, null, false),
    ('where', 'adverb', 5, 1, true, 1, 'in or to what place or position', 'איפה', 'A1', 'high', 'דובר עברית מחליף בכתיב בין where לבין were כי ה-h שקטה.', null, false),
    ('most', 'determiner', 4, 1, true, 1, 'nearly all of a group or an amount', 'רוב', 'A2', 'high', 'בעברית אומרים ''רוב האנשים'' בסמיכות, ולכן דובר עברית שוכח את of וכותב most the people.', null, false),
    ('should', 'verb', 6, 1, true, 1, 'used to say what is the right or best thing to do', 'צריך', 'A2', 'high', 'בעברית ''צריך'' מכסה חובה והמלצה כאחת, ולכן דובר עברית מחליף should ב-must.', 'צריך = should · must · need', false),
    ('need', 'verb', 4, 1, false, 1, 'to require something because it is necessary or very important', 'להזדקק', 'A1', 'high', 'בעברית ''צריך'' הוא שם תואר, ולכן דובר עברית כותב I am need במקום I need.', 'צריך = need · must · should', false),
    ('much', 'determiner', 4, 1, true, 1, 'a large amount of something that cannot be counted', 'הרבה', 'A1', 'high', 'בעברית ''הרבה'' אינו מבחין בין ספיר ללא-ספיר, ולכן דובר עברית כותב much friends במקום many friends.', 'הרבה = much · many', false),
    ('how', 'adverb', 3, 1, true, 1, 'in what way or by what means something happens', 'איך', 'A1', 'high', 'בעברית שואלים ''איך קוראים לזה'', ולכן דובר עברית כותב how do you call this במקום what do you call this.', null, false),
    ('back', 'adverb', 4, 1, true, 1, 'to or towards the place someone or something came from', 'חזרה', 'A1', 'high', 'בעברית ''חזרה'' ו''שוב'' קרובים, ולכן דובר עברית כותב again במקום back אחרי פועל תנועה.', 'חזרה = back · again', false),
    ('back', 'noun', 4, 1, false, 2, 'the part of the body from the neck to the lower end of the spine', 'גב', 'A2', 'high', null, null, false),
    ('may', 'verb', 3, 1, true, 1, 'used to say that something is possible but not certain', 'עשוי', 'A2', 'high', 'בעברית ''יכול'' מכסה גם יכולת וגם אפשרות, ולכן דובר עברית כותב can במקום may.', 'יכול = may · can', false),
    ('such', 'determiner', 4, 1, true, 1, 'of the type already mentioned', 'כזה', 'A2', 'medium', 'בעברית ''כל כך'' ו''כזה'' קרובים, ולכן דובר עברית כותב so a long day במקום such a long day.', 'כזה = such · like this', false),
    ('us', 'pronoun', 2, 1, true, 1, 'the form of we used as the object of a verb or preposition', 'אותנו', 'A1', 'high', 'בעברית ''אנחנו'' ו''אותנו'' באים מאותו שורש, ולכן דובר עברית כותב we אחרי פועל או מילת יחס במקום us.', null, false),
    ('here', 'adverb', 4, 1, true, 1, 'in, at or to this place', 'כאן', 'A1', 'high', 'here ו-hear נשמעות זהה, ודובר עברית מחליף ביניהן בכתיב.', null, false),
    ('really', 'adverb', 6, 2, true, 1, 'used to make a statement stronger, or to say what is true', 'באמת', 'A1', 'high', 'בעברית ''ממש'' משמש כמגביר, ולכן דובר עברית כותב real good במקום really good.', 'ממש = really · truly', false),
    ('even', 'adverb', 4, 2, true, 1, 'used to show that something is surprising or unexpected', 'אפילו', 'A2', 'high', 'בעברית ''אפילו'' יכול לבוא בסוף המשפט, ולכן דובר עברית מציב את even רחוק מהמילה שהוא מדגיש.', null, false),
    ('those', 'determiner', 5, 1, true, 1, 'used for people or things that are far from you, when there is more than one', 'אלו', 'A1', 'high', 'בעברית ''אלו'' ו''אלה'' מתחלפים בחופשיות, ולכן דובר עברית אינו מבחין בין those הרחוק ל-these הקרוב.', 'אלה = these · those', false),
    ('many', 'determiner', 4, 2, true, 1, 'a large number of things or people that can be counted', 'הרבה', 'A1', 'high', 'דובר עברית מחליף בין many ל-much כי ''הרבה'' אחד, וגם מבלבל בכתיב בין many ל-money.', 'הרבה = many · much', false),
    ('child', 'noun', 5, 1, false, 1, 'a young person who is not yet an adult', 'ילד', 'A1', 'high', 'רבים של child הוא children ולא childs, ודובר עברית שמחיל את כלל ה-s טועה.', 'ילד = child · boy · kid', false),
    ('last', 'adjective', 4, 1, false, 1, 'coming after all the others in time or order', 'אחרון', 'A1', 'high', null, null, false),
    ('last', 'verb', 4, 1, false, 2, 'to continue for a period of time', 'להימשך', 'B1', 'high', null, null, false),
    ('call', 'verb', 4, 1, false, 1, 'to speak to someone on the telephone', 'להתקשר', 'A1', 'high', 'בעברית ''לקרוא'' הוא גם call וגם read, ולכן דובר עברית מחליף ביניהם.', 'לקרוא = call · read', false),
    ('call', 'verb', 4, 1, false, 2, 'to give someone or something a particular name', 'לכנות', 'A2', 'high', null, null, false),
    ('down', 'adverb', 4, 1, true, 1, 'towards or in a lower place or position', 'למטה', 'A1', 'high', null, 'למטה = down · below', false),
    ('yes', 'interjection', 3, 1, true, 1, 'used to give a positive answer or to agree', 'כן', 'A1', 'high', null, null, false),
    ('before', 'preposition', 6, 2, true, 1, 'earlier than a particular time or event', 'לפני', 'A1', 'high', 'בעברית ''לפני שבוע'' ו''לפני הדלת'' משתמשים באותה מילה, ולכן דובר עברית כותב before a week במקום a week ago.', 'לפני = before · in front of · ago', false),
    ('man', 'noun', 3, 1, false, 1, 'an adult male human being', 'גבר', 'A1', 'high', 'בעברית ''אדם'' מכסה גם ''בן אדם'' וגם ''גבר'', ולכן דובר עברית כותב man כשהכוונה person.', 'אדם = man · person · human', false),
    ('through', 'preposition', 7, 1, true, 1, 'from one end or side of something to the other', 'דרך', 'A2', 'high', 'דובר עברית מחליף בכתיב בין through, though ו-thought, ומשתמש ב-way במקום through.', 'דרך = through · way', false),
    ('show', 'verb', 4, 1, false, 1, 'to let someone see something, or to point it out to them', 'להראות', 'A1', 'high', 'בעברית ''להראות'' ו''להיראות'' נבדלות בניקוד בלבד, ולכן דובר עברית מחליף בין show ל-look.', 'להראות = show · point', false),
    ('show', 'noun', 4, 1, false, 2, 'a performance for an audience, on a stage or on television', 'מופע', 'A2', 'high', null, null, false),
    ('life', 'noun', 4, 1, false, 1, 'the period between birth and death, or the state of being alive', 'חיים', 'A1', 'high', 'בעברית ''חיים'' הוא ריבוי, ולכן דובר עברית כותב my lifes are good במקום my life is good.', 'חיים = life · living', false)
), w as (
  insert into public.words (headword, pos, origin, n_letters, n_syllables, is_function_word)
  select distinct on (headword, pos) headword, pos, 'generated', n_letters, n_syllables, is_function_word
  from incoming
  order by headword, pos
  on conflict (headword, pos) do update set headword = excluded.headword
  returning id, headword, pos
)
insert into public.senses (word_id, sense_index, definition_en, translation_he, cefr_level,
                           translation_confidence, he_interference_note, he_one_to_many_group,
                           generation_run_id, needs_human_review)
select w.id, i.sense_index, i.definition_en, i.translation_he, i.cefr_level,
       i.translation_confidence, i.he_interference_note, i.he_one_to_many_group,
       run.id, i.needs_human_review
from incoming i
join w on w.headword = i.headword and w.pos = i.pos
cross join run
on conflict (word_id, sense_index) do nothing;

-- --------------------------------------------------------------------------
-- batch-2026-08-09.jsonl — 60 of 60 rows pass the gate
-- --------------------------------------------------------------------------
with run as (
  insert into public.generation_runs (model, prompt_version, requested, accepted, rejected, notes)
  values ('claude-opus-5', 'content-agent/2026-08-09', 45, 60, 0, 'batch-2026-08-09.jsonl')
  returning id
), incoming (headword, pos, n_letters, n_syllables, is_function_word, sense_index,
            definition_en, translation_he, cefr_level, translation_confidence,
            he_interference_note, he_one_to_many_group, needs_human_review) as (
  values
    ('the', 'determiner', 3, 1, true, 1, 'used before a noun that the listener can already identify', 'ה־', 'A1', 'high', 'ה׳ הידיעה בעברית נצמדת למילה עצמה, ובאנגלית היא מילה נפרדת שעומדת לפני שם העצם ולפני שם התואר שלו.', null, false),
    ('be', 'verb', 2, 1, false, 1, 'to exist, or to have a particular quality or position', 'להיות', 'A1', 'high', 'בעברית משפט בהווה נכתב בלי פועל ("הוא מורה"), ולכן דוברי עברית משמיטים את be באנגלית.', null, false),
    ('of', 'preposition', 2, 1, true, 1, 'belonging to or connected with someone or something', 'של', 'A1', 'high', 'בעברית סדר המילים הוא "הדלת של המכונית"; באנגלית אפשר גם "the car''s door", ודוברי עברית נוטים להעדיף תמיד of.', 'של = of · צורת הקניין באנגלית', false),
    ('of', 'preposition', 2, 1, true, 2, 'used to show that something is part of a larger group or amount', 'מתוך', 'A2', 'high', null, null, false),
    ('and', 'conjunction', 3, 1, true, 1, 'used to join two words, phrases or clauses', 'וגם', 'A1', 'high', null, null, false),
    ('to', 'preposition', 2, 1, true, 1, 'showing the place or person that something moves towards', 'אל', 'A1', 'high', 'האות ל־ בעברית משמשת גם לכיוון וגם למקבל הפעולה, ולכן דוברי עברית מבלבלים בין to לבין for.', 'ל = to · for', false),
    ('a', 'determiner', 1, 1, true, 1, 'used before a noun to show it is one that has not been mentioned before', 'כלשהו', 'A1', 'low', 'בעברית אין תווית ליחיד לא מיודע, ולכן דוברי עברית משמיטים את a לפני שם עצם יחיד ("he is teacher").', null, true),
    ('in', 'preposition', 2, 1, true, 1, 'inside something, or surrounded by it', 'בתוך', 'A1', 'high', 'האות ב־ בעברית מכסה in, at ו-on, ולכן דוברי עברית בוחרים ביניהן כמעט באקראי.', 'ב = in · at · on', false),
    ('have', 'verb', 4, 1, false, 1, 'to own something, or to hold it as yours', 'יש ל־', 'A1', 'high', 'בעברית אומרים "יש לי ספר" בלי פועל שייכות, ולכן דוברי עברית כותבים "to me there is a book" במקום I have a book.', null, false),
    ('have', 'verb', 4, 1, false, 2, 'to eat or drink something', 'לאכול', 'A2', 'high', 'בעברית אומרים "לאכול ארוחת בוקר", ולכן דוברי עברית כותבים "eat breakfast" במקום have breakfast.', null, false),
    ('it', 'pronoun', 2, 1, true, 1, 'the thing or animal that was just mentioned', 'זה', 'A1', 'high', 'בעברית משפט מזג אוויר נכתב בלי נושא ("יורד גשם"), ולכן דוברי עברית משמיטים את it ב-"it is raining".', 'זה = it · this · that', false),
    ('you', 'pronoun', 3, 1, true, 1, 'the person or people the speaker is talking to', 'אתה', 'A1', 'high', 'בעברית יש צורת זכר ונקבה ויחיד ורבים לגוף שני; באנגלית you מכסה את כולן, ודוברי עברית מחפשים צורה נפרדת לרבים.', null, false),
    ('for', 'preposition', 3, 1, true, 1, 'showing who will get something or why it is done', 'בשביל', 'A1', 'high', null, 'ל = to · for', false),
    ('for', 'preposition', 3, 1, true, 2, 'used to show how long something continues', 'במשך', 'A2', 'high', null, null, false),
    ('not', 'adverb', 3, 1, true, 1, 'used to make a word or sentence negative', 'לא', 'A1', 'high', null, null, false),
    ('that', 'determiner', 4, 1, true, 1, 'used to point to a person or thing further away from the speaker', 'ההוא', 'A1', 'high', null, 'זה = it · this · that', false),
    ('that', 'conjunction', 4, 1, true, 2, 'used to introduce a clause after verbs such as say, know or think', 'ש־', 'A2', 'high', 'בעברית ש־ נצמדת למילה הבאה אחריה; באנגלית that היא מילה נפרדת, ודוברי עברית משמיטים אותה.', null, false),
    ('on', 'preposition', 2, 1, true, 1, 'touching and supported by the top surface of something', 'על', 'A1', 'high', null, 'ב = in · at · on', false),
    ('on', 'preposition', 2, 1, true, 2, 'having something as its subject', 'בנושא', 'B1', 'high', null, null, false),
    ('with', 'preposition', 4, 1, true, 1, 'in the company of someone or something', 'עם', 'A1', 'high', null, null, false),
    ('with', 'preposition', 4, 1, true, 2, 'using a particular tool or thing', 'באמצעות', 'A2', 'high', 'בעברית ב־ מכסה גם "עם" וגם "באמצעות", ולכן דוברי עברית כותבים by a knife במקום with a knife.', null, false),
    ('do', 'verb', 2, 1, false, 1, 'to perform an action or piece of work', 'לעשות', 'A1', 'high', 'בעברית "לעשות" מכסה גם do וגם make, ולכן דוברי עברית כותבים "do a mistake" במקום make a mistake.', 'לעשות = do · make', false),
    ('as', 'preposition', 2, 1, true, 1, 'in the job or role of something', 'בתור', 'A2', 'high', null, null, false),
    ('as', 'conjunction', 2, 1, true, 2, 'at the same time that something else happens', 'כאשר', 'B1', 'high', null, null, false),
    ('he', 'pronoun', 2, 1, true, 1, 'the male person or animal that was just mentioned', 'הוא', 'A1', 'high', null, null, false),
    ('we', 'pronoun', 2, 1, true, 1, 'the speaker together with at least one other person', 'אנחנו', 'A1', 'high', null, null, false),
    ('this', 'determiner', 4, 1, true, 1, 'used to point to a person or thing that is near the speaker', 'הזה', 'A1', 'high', null, 'זה = it · this · that', false),
    ('at', 'preposition', 2, 1, true, 1, 'in a particular place', 'ב־', 'A1', 'high', null, 'ב = in · at · on', false),
    ('at', 'preposition', 2, 1, true, 2, 'used before a point in time', 'בשעה', 'A1', 'high', null, null, false),
    ('they', 'pronoun', 4, 1, true, 1, 'the people, animals or things that were just mentioned', 'הם', 'A1', 'high', null, null, false),
    ('but', 'conjunction', 3, 1, true, 1, 'used to introduce something that is different or surprising', 'אבל', 'A1', 'high', null, null, false),
    ('from', 'preposition', 4, 1, true, 1, 'showing the place or time where something starts', 'מן', 'A1', 'high', 'ההיפוך form/from הוא שגיאת כתיב נפוצה מאוד אצל דוברי עברית, שקוראים אנגלית מהר משמאל לימין.', 'מ = from · of', false),
    ('by', 'preposition', 2, 1, true, 1, 'showing who or what does the action in a passive sentence', 'על ידי', 'B1', 'high', null, null, false),
    ('by', 'preposition', 2, 1, true, 2, 'next to or very near something', 'ליד', 'A2', 'high', null, null, false),
    ('will', 'verb', 4, 1, true, 1, 'used to show that something is going to happen in the future', 'עתיד', 'A1', 'medium', 'בעברית העתיד מסומן בתוך הפועל עצמו ("אקרא"), ולכן דוברי עברית שוכחים את מילת העזר will.', null, false),
    ('or', 'conjunction', 2, 1, true, 1, 'used to join two choices when only one is possible', 'או', 'A1', 'high', null, null, false),
    ('his', 'determiner', 3, 1, true, 1, 'belonging to the male person who was just mentioned', 'שלו', 'A1', 'high', null, 'שלו = his · its', false),
    ('say', 'verb', 3, 1, false, 1, 'to speak words in order to express something', 'לומר', 'A1', 'high', 'בעברית "אמר לי" ו"סיפר לי" קרובים מאוד, ולכן דוברי עברית כותבים "he said me" במקום he told me.', 'לומר = say · tell', false),
    ('go', 'verb', 2, 1, false, 1, 'to move or travel from one place to another', 'ללכת', 'A1', 'high', 'בעברית "ללכת" מכסה גם go וגם walk, ולכן דוברי עברית כותבים "I went by foot" במקום I walked.', null, false),
    ('she', 'pronoun', 3, 1, true, 1, 'the female person or animal that was just mentioned', 'היא', 'A1', 'high', null, null, false),
    ('so', 'adverb', 2, 1, true, 1, 'to a very great degree', 'כל כך', 'A2', 'high', null, null, false),
    ('so', 'conjunction', 2, 1, true, 2, 'for that reason', 'לכן', 'A2', 'high', null, null, false),
    ('all', 'determiner', 3, 1, true, 1, 'the whole number or amount of something', 'כל', 'A1', 'high', null, null, false),
    ('about', 'preposition', 5, 2, true, 1, 'on the subject of someone or something', 'בנוגע ל־', 'A1', 'high', null, null, false),
    ('about', 'adverb', 5, 2, true, 2, 'a little more or a little less than a number', 'בערך', 'A2', 'high', null, null, false),
    ('if', 'conjunction', 2, 1, true, 1, 'used to say that one thing depends on another', 'אם', 'A1', 'high', null, null, false),
    ('one', 'determiner', 3, 1, true, 1, 'the number that comes before two in counting', 'אחד', 'A1', 'high', null, null, false),
    ('my', 'determiner', 2, 1, true, 1, 'belonging to the person who is speaking', 'שלי', 'A1', 'high', null, 'שלי = my · mine', false),
    ('know', 'verb', 4, 1, false, 1, 'to have information about something in your mind', 'לדעת', 'A1', 'high', 'בעברית "לדעת" מכסה גם know בעובדות וגם know בהיכרות עם אדם; באנגלית ההיכרות היא know בלבד, לא "learn".', 'לדעת = know · can (a skill)', false),
    ('know', 'verb', 4, 1, false, 2, 'to be familiar with a person or place', 'להכיר', 'A2', 'high', 'דוברי עברית משתמשים ב-meet במקום know כדי לתאר היכרות קיימת ("I met him for years").', 'להכיר = know · meet', false),
    ('there', 'adverb', 5, 1, true, 1, 'in or at that place', 'שם', 'A1', 'high', null, null, false),
    ('there', 'pronoun', 5, 1, true, 2, 'used with be to say that something exists', 'יש', 'A1', 'high', 'בעברית אומרים "יש ספר על השולחן" בלי מילת נושא, ולכן דוברי עברית משמיטים את there ב-there is.', null, false),
    ('which', 'determiner', 5, 1, true, 1, 'used to ask about one thing out of a limited group', 'איזה', 'A2', 'high', null, null, false),
    ('can', 'verb', 3, 1, true, 1, 'to be able to do something', 'יכול', 'A1', 'high', 'בעברית "יכול" מקבל צורת זכר ונקבה ורבים; באנגלית can אינו משתנה, ודוברי עברית מוסיפים לו s.', null, false),
    ('can', 'noun', 3, 1, false, 2, 'a closed metal container for food or drink', 'פחית', 'A2', 'high', null, null, false),
    ('get', 'verb', 3, 1, false, 1, 'to receive or obtain something', 'לקבל', 'A1', 'high', null, null, false),
    ('get', 'verb', 3, 1, false, 2, 'to arrive at a place', 'להגיע', 'A2', 'high', 'דוברי עברית משתמשים ב-arrive בכל מקרה; באנגלית מדוברת get to הוא הצורה הרגילה.', null, false),
    ('her', 'determiner', 3, 1, true, 1, 'belonging to the female person who was just mentioned', 'שלה', 'A1', 'high', null, 'שלה = her · hers', false),
    ('would', 'verb', 5, 1, true, 1, 'used to talk about something that is possible but not real', 'היה', 'B1', 'medium', 'בעברית התנאי הבלתי קיים נבנה עם "היה" ("הייתי נוסע"), ולכן דוברי עברית כותבים "I was travel" במקום I would travel.', null, false),
    ('think', 'verb', 5, 1, false, 1, 'to have an opinion or belief about something', 'לחשוב', 'A1', 'high', null, null, false)
), w as (
  insert into public.words (headword, pos, origin, n_letters, n_syllables, is_function_word)
  select distinct on (headword, pos) headword, pos, 'generated', n_letters, n_syllables, is_function_word
  from incoming
  order by headword, pos
  on conflict (headword, pos) do update set headword = excluded.headword
  returning id, headword, pos
)
insert into public.senses (word_id, sense_index, definition_en, translation_he, cefr_level,
                           translation_confidence, he_interference_note, he_one_to_many_group,
                           generation_run_id, needs_human_review)
select w.id, i.sense_index, i.definition_en, i.translation_he, i.cefr_level,
       i.translation_confidence, i.he_interference_note, i.he_one_to_many_group,
       run.id, i.needs_human_review
from incoming i
join w on w.headword = i.headword and w.pos = i.pos
cross join run
on conflict (word_id, sense_index) do nothing;

-- --------------------------------------------------------------------------
-- batch-2026-08-10.jsonl — 64 of 64 rows pass the gate
-- --------------------------------------------------------------------------
with run as (
  insert into public.generation_runs (model, prompt_version, requested, accepted, rejected, notes)
  values ('claude-opus-5', 'content-agent/2026-08-10', 45, 64, 0, 'batch-2026-08-10.jsonl')
  returning id
), incoming (headword, pos, n_letters, n_syllables, is_function_word, sense_index,
            definition_en, translation_he, cefr_level, translation_confidence,
            he_interference_note, he_one_to_many_group, needs_human_review) as (
  values
    ('like', 'verb', 4, 1, false, 1, 'to enjoy something or find it pleasant', 'לאהוב', 'A1', 'high', 'העברית משתמשת ב''אוהב'' גם ל-like וגם ל-love, ולכן דוברי עברית אומרים I love it על דברים שהם רק מחבבים.', 'לאהוב — like · love', false),
    ('like', 'preposition', 4, 1, true, 2, 'similar to something or someone', 'כמו', 'A2', 'high', 'בעברית ''כמו'' משמש גם להשוואה וגם לתפקיד של as, ולכן דוברי עברית כותבים She works like a teacher במקום as a teacher.', 'כמו — like · as', false),
    ('more', 'determiner', 4, 1, true, 1, 'a greater amount or number of something', 'יותר', 'A1', 'high', 'בעברית משווים עם ''יותר'' לפני שם התואר, ולכן דוברי עברית כותבים more big במקום bigger.', 'יותר — more · -er', false),
    ('their', 'determiner', 5, 1, true, 1, 'belonging to those people or things', 'שלהם', 'A1', 'high', 'there · their נשמעות זהות, ודוברי עברית שלומדים מהאוזן כותבים there במקום their.', null, false),
    ('your', 'determiner', 4, 1, true, 1, 'belonging to the person being spoken to', 'שלך', 'A1', 'high', 'בעברית ''שלך'' משתנה לפי מין הנמען, ובאנגלית your אחד לכולם — ולכן דוברי עברית מחפשים צורת נקבה שאינה קיימת.', null, false),
    ('when', 'conjunction', 4, 1, true, 1, 'at the time that something happens', 'כאשר', 'A1', 'high', 'בשאלה עקיפה האנגלית שומרת על סדר של משפט חיובי, ודוברי עברית כותבים I don''t know when does he come.', null, false),
    ('when', 'adverb', 4, 1, true, 2, 'at what time', 'מתי', 'A1', 'high', 'דוברי עברית שואלים When you are coming? כי בעברית אין היפוך נושא ופועל בשאלה.', null, false),
    ('what', 'pronoun', 4, 1, true, 1, 'which thing or things', 'מה', 'A1', 'high', 'דוברי עברית משמיטים את do ושואלים What book you want? במקום What book do you want?', null, false),
    ('make', 'verb', 4, 1, false, 1, 'to produce or create something', 'לעשות', 'A1', 'high', 'בעברית ''לעשות'' מכסה גם do וגם make, ולכן דוברי עברית אומרים do a cake ו-make homework.', 'לעשות — do · make', false),
    ('make', 'verb', 4, 1, false, 2, 'to cause someone to do or feel something', 'לגרום', 'B1', 'high', 'אחרי make בא פועל בלי to, ודוברי עברית מוסיפים to בגלל ''לגרום לו לחכות'' וכותבים make him to wait.', null, false),
    ('time', 'noun', 4, 1, false, 1, 'the passing of hours, days and years', 'זמן', 'A1', 'high', 'בעברית ''זמן'' ו''פעם'' הן מילים שונות, ובאנגלית שתיהן time — ולכן דוברי עברית מתלבטים בין much time לבין many times.', null, false),
    ('time', 'noun', 4, 1, false, 2, 'one of several occasions on which something happens', 'פעם', 'A2', 'high', 'דוברי עברית שוכחים את סימן הרבים ואומרים many time במקום many times.', null, false),
    ('who', 'pronoun', 3, 1, true, 1, 'which person or people', 'מי', 'A1', 'high', 'בעברית ''מי'' משמש גם לשאלה וגם לזיקה, ובאנגלית משפט זיקה על חפץ דורש which או that ולא who.', null, false),
    ('see', 'verb', 3, 1, false, 1, 'to notice something with your eyes', 'לראות', 'A1', 'high', 'דוברי עברית מערבבים see עם look at וכותבים I see at the picture.', null, false),
    ('see', 'verb', 3, 1, false, 2, 'to understand something', 'להבין', 'B1', 'high', 'דוברי עברית מגיבים I understand גם כשהאנגלית הטבעית בשיחה היא I see.', null, false),
    ('up', 'adverb', 2, 1, true, 1, 'toward a higher place or position', 'למעלה', 'A1', 'high', 'בעברית ''למעלה'' עומדת בפני עצמה, ובאנגלית up נצמד לפועל ומשנה משמעות (give up · look up) — ודוברי עברית מתרגמים מילולית.', null, false),
    ('people', 'noun', 6, 2, false, 1, 'men, women and children in general', 'אנשים', 'A1', 'high', 'דוברי עברית מוסיפים s ואומרים peoples, כי בעברית ''אנשים'' כבר נושא סימן רבים גלוי.', null, false),
    ('some', 'determiner', 4, 1, true, 1, 'an unstated number of people or things', 'כמה', 'A1', 'medium', 'בעברית ''כמה'' משמש גם ל-some וגם ל-how many, ולכן דוברי עברית מערבבים בין השאלה לבין הכמות.', 'כמה — some · how many · a few', false),
    ('out', 'adverb', 3, 1, true, 1, 'away from the inside of a place', 'החוצה', 'A1', 'high', 'צירופי out אינם מילוליים (find out · run out), ודוברי עברית מתרגמים ''החוצה'' ומאבדים את משמעות הצירוף.', null, false),
    ('me', 'pronoun', 2, 1, true, 1, 'the person speaking, as the object of a verb', 'אותי', 'A1', 'high', 'בעברית ''אותי'' ו''לי'' הן צורות שונות, ובאנגלית שתיהן me — ולכן דוברי עברית מתלבטים אם צריך to לפני me.', null, false),
    ('good', 'adjective', 4, 1, false, 1, 'of high quality, or pleasant', 'טוב', 'A1', 'high', 'בעברית ''טוב'' משמש גם כשם תואר וגם כתואר הפועל, ולכן דוברי עברית אומרים She speaks good במקום She speaks well.', 'טוב — good · well · fine', false),
    ('other', 'determiner', 5, 2, true, 1, 'different from the one already mentioned', 'אחר', 'A1', 'high', 'בעברית ''אחר'' מכסה other · another · different, ולכן דוברי עברית כותבים I want other book במקום another book.', 'אחר — other · another · different', false),
    ('year', 'noun', 4, 1, false, 1, 'a period of twelve months', 'שנה', 'A1', 'high', 'דוברי עברית משמיטים את old בציון גיל ואומרים She is ten years, כי בעברית ''היא בת עשר'' אינו דורש מילה נוספת.', null, false),
    ('well', 'adverb', 4, 1, false, 1, 'in a good way, to a high standard', 'היטב', 'A1', 'high', 'דוברי עברית אומרים He speaks good, כי ''טוב'' בעברית משמש גם כתואר הפועל.', 'טוב — good · well · fine', false),
    ('well', 'noun', 4, 1, false, 2, 'a deep hole in the ground that water comes from', 'באר', 'B1', 'high', null, null, false),
    ('our', 'determiner', 3, 1, true, 1, 'belonging to us', 'שלנו', 'A1', 'high', 'בעברית ''שלנו'' בא אחרי שם העצם, ובאנגלית our בא לפניו — ודוברי עברית כותבים the house our.', null, false),
    ('very', 'adverb', 4, 2, true, 1, 'to a great degree', 'מאוד', 'A1', 'high', 'בעברית ''מאוד'' יכול לבוא אחרי שם התואר, ובאנגלית very חייב לבוא לפניו — ודוברי עברית כותבים big very.', null, false),
    ('just', 'adverb', 4, 1, true, 1, 'only, and nothing more', 'רק', 'A2', 'high', 'בעברית ''רק'' ו''לפני רגע'' הן מילים שונות, ובאנגלית שתיהן just — ולכן דוברי עברית אינם בטוחים איזו משמעות נקראת.', 'רק — only · just', false),
    ('just', 'adverb', 4, 1, true, 2, 'a very short time ago', 'לפני רגע', 'A2', 'high', 'באנגלית just במשמעות הזו בא עם have (I have just eaten), ודוברי עברית משמיטים את have כי בעברית די בעבר פשוט.', null, false),
    ('them', 'pronoun', 4, 1, true, 1, 'those people or things, as the object of a verb', 'אותם', 'A1', 'high', 'בעברית ''אותם'' משתנה לפי מין, ובאנגלית them אחד לכולם — ודוברי עברית מחפשים צורת נקבה שאינה קיימת.', null, false),
    ('no', 'determiner', 2, 1, true, 1, 'not any', 'שום', 'A1', 'high', 'בעברית שלילה כפולה תקנית (''אין לי כלום''), ובאנגלית no כבר שולל — ולכן דוברי עברית כותבים I don''t have no money.', null, false),
    ('no', 'interjection', 2, 1, false, 2, 'a word used to give a negative answer', 'לא', 'A1', 'high', 'בעברית ''לא'' משמש גם כתשובה וגם כשלילת פועל, ולכן דוברי עברית אומרים I no want במקום I do not want.', 'לא — no · not', false),
    ('take', 'verb', 4, 1, false, 1, 'to move something or someone with you', 'לקחת', 'A1', 'high', 'דוברי עברית מבלבלים בין take לבין bring, כי בעברית כיוון התנועה אינו מסומן באותו אופן.', null, false),
    ('take', 'verb', 4, 1, false, 2, 'to need a length of time', 'להימשך', 'A2', 'high', 'בעברית אומרים ''זה לוקח שעה'', ובאנגלית הנושא הוא it — ודוברי עברית משמיטים אותו וכותבים Takes an hour.', null, false),
    ('because', 'conjunction', 7, 2, true, 1, 'for the reason that', 'כי', 'A1', 'high', 'דוברי עברית משמיטים את of ואומרים because the rain, כי בעברית ''בגלל'' היא מילה אחת.', null, false),
    ('come', 'verb', 4, 1, false, 1, 'to move toward the person speaking or to a place', 'לבוא', 'A1', 'high', 'בעברית ''לבוא'' ו''ללכת'' אינם תלויים במיקום הדובר כמו come ו-go, ולכן דוברי עברית אומרים I will go to you.', null, false),
    ('could', 'verb', 5, 1, true, 1, 'was able to do something in the past', 'יכול היה', 'A2', 'high', 'בעברית ''יכולתי'' צורה אחת, ובאנגלית could משמש גם לעבר וגם לבקשה מנומסת — ודוברי עברית קוראים כל could כעבר.', null, false),
    ('could', 'verb', 5, 1, true, 2, 'used to ask for something politely', 'אפשר', 'A2', 'medium', 'בעברית מבקשים עם ''אפשר?'' בלי נושא, ולכן דוברי עברית משמיטים את you ושואלים Could open the window?', null, false),
    ('use', 'verb', 3, 1, false, 1, 'to do something with a thing for a purpose', 'להשתמש', 'A1', 'high', 'בעברית ''להשתמש ב'' דורש מילת יחס, ובאנגלית use אינו דורש — ולכן דוברי עברית כותבים use in the phone.', null, false),
    ('use', 'noun', 3, 1, false, 2, 'the act of using something', 'שימוש', 'A2', 'high', 'בעברית שם הפועל ושם העצם נבדלים בבניין, ובאנגלית הכתיב זהה והשוני רק בהגייה — ודוברי עברית מבטאים את שם העצם כפועל.', null, false),
    ('between', 'preposition', 7, 2, true, 1, 'in the space or time that separates two things', 'בין', 'A1', 'high', 'בעברית ''בין X ל-Y'', ובאנגלית משתמשים ב-and — ולכן דוברי עברית כותבים between the school to the park.', 'בין — between · among', false),
    ('lot', 'noun', 3, 1, false, 1, 'a large amount or number of something', 'הרבה', 'A1', 'high', 'בעברית ''הרבה'' אחד לספירים ולבלתי ספירים, ולכן דוברי עברית כותבים much books במקום many books.', 'הרבה — a lot · many · much', false),
    ('feel', 'verb', 4, 1, false, 1, 'to experience an emotion or a physical state', 'להרגיש', 'A1', 'high', 'דוברי עברית מוסיפים myself ואומרים I feel myself good, בעקבות ''אני מרגיש טוב''.', null, false),
    ('feel', 'verb', 4, 1, false, 2, 'to touch something in order to learn about it', 'למשש', 'B1', 'high', null, null, false),
    ('long', 'adjective', 4, 1, false, 1, 'great in distance or in time', 'ארוך', 'A1', 'high', 'דוברי עברית מתרגמים ''כמה זמן'' ל-how much time, ובאנגלית שואלים How long.', null, false),
    ('too', 'adverb', 3, 1, true, 1, 'in addition, as well', 'גם', 'A1', 'high', 'בעברית ''גם'' בא לפני המילה, ובאנגלית too בא בסוף המשפט — ולכן דוברי עברית כותבים Too I want.', 'גם — too · also · as well', false),
    ('too', 'adverb', 3, 1, true, 2, 'more than is needed or wanted', 'מדי', 'A2', 'high', 'דוברי עברית משתמשים ב-too במקום very ואומרים The film was too good כשהכוונה חיובית.', null, false),
    ('pause', 'noun', 5, 1, false, 1, 'a short stop in speaking or in action', 'הפסקה', 'B1', 'high', 'בעברית ''הפסקה'' משמשת גם להפסקה בבית ספר, ולכן דוברי עברית אומרים pause במקום break.', 'הפסקה — pause · break', false),
    ('pause', 'verb', 5, 1, false, 2, 'to stop for a short time before going on', 'לעצור לרגע', 'B1', 'high', null, null, false),
    ('still', 'adverb', 5, 1, true, 1, 'continuing now as before', 'עדיין', 'A2', 'high', 'בעברית ''עדיין'' אחד ל-still ול-yet, ולכן דוברי עברית כותבים He is not ready still במקום not ready yet.', 'עדיין — still · yet', false),
    ('still', 'adjective', 5, 1, false, 2, 'not moving at all', 'דומם', 'B1', 'medium', null, null, false),
    ('write', 'verb', 5, 1, false, 1, 'to make letters and words on a surface', 'לכתוב', 'A1', 'high', 'ב-write יש w אילם, ודוברי עברית שלומדים מהאוזן כותבים rite.', null, false),
    ('talk', 'verb', 4, 1, false, 1, 'to say things to someone', 'לדבר', 'A1', 'high', 'בעברית ''לדבר'' אחד ל-talk ול-speak, ולכן דוברי עברית אומרים I speak with my friend every day במקום talk.', 'לדבר — talk · speak', false),
    ('talk', 'noun', 4, 1, false, 2, 'a speech given to a group of people', 'הרצאה', 'B1', 'high', null, null, false),
    ('try', 'verb', 3, 1, false, 1, 'to make an effort to do something', 'לנסות', 'A1', 'high', 'אחרי try בא to לפני הפועל, ודוברי עברית משמיטים אותו וכותבים I try finish it.', null, false),
    ('something', 'pronoun', 9, 2, true, 1, 'a thing that is not named or not known', 'משהו', 'A1', 'high', 'בעברית ''משהו'' משמש גם בשאלה ובשלילה, ולכן דוברי עברית כותבים I don''t want something במקום anything.', 'משהו — something · anything', false),
    ('unclear', 'adjective', 7, 2, false, 1, 'not easy to understand or to see', 'לא ברור', 'B1', 'high', 'בעברית ''לא ברור'' הן שתי מילים, ולכן דוברי עברית כותבים not clear גם היכן שהאנגלית הטבעית היא unclear.', null, false),
    ('same', 'adjective', 4, 1, false, 1, 'not different from another thing or person', 'זהה', 'A1', 'high', 'same תמיד בא עם the, ודוברי עברית משמיטים אותו ואומרים We have same idea.', null, false),
    ('great', 'adjective', 5, 1, false, 1, 'very good or enjoyable', 'נהדר', 'A1', 'high', 'בעברית ''נהדר'' ו''גדול'' מילים שונות, ובאנגלית great מכסה את שתיהן — ולכן דוברי עברית קוראים a great man כ''איש גדול''.', null, false),
    ('great', 'adjective', 5, 1, false, 2, 'very large in amount or degree', 'רב', 'B2', 'high', null, null, false),
    ('number', 'noun', 6, 2, false, 1, 'a word or sign that stands for an amount', 'מספר', 'A1', 'high', 'בעברית ''מספר'' הוא גם number וגם ''כמה'', ולכן דוברי עברית כותבים a number of days כשהכוונה a few days.', 'מספר — number · several', false),
    ('number', 'noun', 6, 2, false, 2, 'how many people or things there are', 'כמות', 'A2', 'high', 'אחרי the number of בא פועל ביחיד, ודוברי עברית כותבים The number of people are large.', null, false),
    ('little', 'adjective', 6, 2, false, 1, 'small in size', 'קטן', 'A1', 'high', 'בעברית ''קטן'' אחד ל-little ול-small, ולכן דוברי עברית אומרים The dog is little כשהאנגלית הטבעית היא small.', 'קטן — little · small', false),
    ('little', 'determiner', 6, 2, true, 2, 'not much of something', 'מעט', 'A2', 'high', 'בעברית ''מעט'' אחד לספירים ולבלתי ספירים, ולכן דוברי עברית כותבים little books במקום few books.', 'מעט — little · few', false)
), w as (
  insert into public.words (headword, pos, origin, n_letters, n_syllables, is_function_word)
  select distinct on (headword, pos) headword, pos, 'generated', n_letters, n_syllables, is_function_word
  from incoming
  order by headword, pos
  on conflict (headword, pos) do update set headword = excluded.headword
  returning id, headword, pos
)
insert into public.senses (word_id, sense_index, definition_en, translation_he, cefr_level,
                           translation_confidence, he_interference_note, he_one_to_many_group,
                           generation_run_id, needs_human_review)
select w.id, i.sense_index, i.definition_en, i.translation_he, i.cefr_level,
       i.translation_confidence, i.he_interference_note, i.he_one_to_many_group,
       run.id, i.needs_human_review
from incoming i
join w on w.headword = i.headword and w.pos = i.pos
cross join run
on conflict (word_id, sense_index) do nothing;

-- --------------------------------------------------------------------------
-- batch-2026-08-11.jsonl — 61 of 61 rows pass the gate
-- --------------------------------------------------------------------------
with run as (
  insert into public.generation_runs (model, prompt_version, requested, accepted, rejected, notes)
  values ('claude-opus-5', 'content-agent/2026-08-11', 45, 61, 0, 'batch-2026-08-11.jsonl')
  returning id
), incoming (headword, pos, n_letters, n_syllables, is_function_word, sense_index,
            definition_en, translation_he, cefr_level, translation_confidence,
            he_interference_note, he_one_to_many_group, needs_human_review) as (
  values
    ('both', 'determiner', 4, 1, true, 1, 'the two people or things together, not only one of them', 'שניהם', 'A1', 'high', 'בעברית אומרים ''שני הספרים'', ולכן דוברי עברית כותבים both the books במקום both books או both of the books.', null, false),
    ('help', 'verb', 4, 1, false, 1, 'to do something useful for somebody so that their work is easier', 'לעזור', 'A1', 'high', 'בהשפעת ''לעזור לי'' דוברי עברית כותבים help to me; באנגלית help לוקח מושא ישיר בלי to.', null, false),
    ('help', 'noun', 4, 1, false, 2, 'the act of making somebody''s work or problem easier', 'עזרה', 'A2', 'high', null, null, false),
    ('own', 'adjective', 3, 1, false, 1, 'belonging to the person just mentioned and to nobody else', 'משלו', 'A2', 'medium', 'דוברי עברית מתרגמים ''החדר שלי'' ל-my own room גם בלי כוונת בעלות בלעדית; own מוסיף ניגוד ל''של מישהו אחר''.', null, false),
    ('own', 'verb', 3, 1, false, 2, 'to have something as your property', 'להיות בעלים של', 'B1', 'medium', 'פועל own אינו קיים בעברית כמילה אחת, ולכן דוברי עברית כותבים I have a car גם כשהכוונה לבעלות ולא להחזקה זמנית.', null, false),
    ('part', 'noun', 4, 1, false, 1, 'a piece or amount of something larger', 'חלק', 'A1', 'high', null, null, false),
    ('country', 'noun', 7, 2, false, 1, 'an area of land with its own government and people', 'מדינה', 'A1', 'high', 'המילה העברית ''ארץ'' מכסה גם country וגם land, ולכן דוברי עברית כותבים land במקום country במשפטים על מדינות.', null, false),
    ('put', 'verb', 3, 1, false, 1, 'to move something into a place or position', 'לשים', 'A1', 'high', null, null, false),
    ('point', 'noun', 5, 1, false, 1, 'an idea or fact that somebody states in a talk or discussion', 'נקודה', 'B1', 'high', null, null, false),
    ('point', 'verb', 5, 1, false, 2, 'to show where something is by holding out your finger', 'להצביע', 'A2', 'high', 'בעברית ''להצביע'' משמש גם להצבעה בבחירות; באנגלית זה vote, ו-point משמש רק לתנועת האצבע.', null, false),
    ('start', 'verb', 5, 1, false, 1, 'to begin doing something, or to begin to happen', 'להתחיל', 'A1', 'high', null, null, false),
    ('start', 'noun', 5, 1, false, 2, 'the first part or first moment of something', 'התחלה', 'A2', 'high', null, null, false),
    ('each', 'determiner', 4, 1, true, 1, 'every one of two or more people or things, seen one by one', 'כל אחד', 'A2', 'high', 'דוברי עברית מציבים each לפני שם עצם ברבים (each students) כי ''כל'' בעברית מופיע גם לפני רבים; each דורש יחיד.', 'כל — each · every · all', false),
    ('become', 'verb', 6, 2, false, 1, 'to begin to be something, or to change into something', 'להפוך ל', 'A2', 'high', 'העברית משתמשת ב''נהיה'' גם ל-become וגם ל-get; דוברי עברית כותבים become angry כשמדובר בשינוי מהיר שבאנגלית דורש get.', null, false),
    ('interest', 'noun', 8, 3, false, 1, 'the wish to know more about somebody or something', 'עניין', 'B1', 'high', null, null, false),
    ('interest', 'noun', 8, 3, false, 2, 'the extra money a bank charges you for a loan', 'ריבית', 'B2', 'high', 'בעברית ''ריבית'' ו''עניין'' הן שתי מילים שונות לגמרי, ולכן דוברי עברית מתקשים לזהות ש-interest נושא את שתי המשמעויות.', null, false),
    ('old', 'adjective', 3, 1, false, 1, 'having lived for a long time', 'זקן', 'A1', 'high', null, 'ישן — old · ancient', false),
    ('old', 'adjective', 3, 1, false, 2, 'made or bought a long time ago; not new', 'ישן', 'A1', 'high', 'המילה ''ישן'' בעברית משמשת גם ל-old וגם ל-asleep, ודוברי עברית מבלבלים בין המילים בכתיבה מהירה.', 'ישן — old · asleep', false),
    ('off', 'adverb', 3, 1, false, 1, 'not working, because the power is not connected', 'כבוי', 'A2', 'high', 'בעברית ''כבוי'' הוא שם תואר, ולכן דוברי עברית כותבים the light is closed בהשפעת ''האור סגור''.', null, false),
    ('off', 'preposition', 3, 1, true, 2, 'away from a surface or a place', 'הרחק מ', 'A2', 'medium', null, null, false),
    ('another', 'determiner', 7, 3, true, 1, 'one more of the same kind', 'עוד אחד', 'A1', 'high', 'דוברי עברית כותבים another books כי ''עוד'' בעברית מופיע גם לפני רבים; another דורש שם עצם ביחיד.', null, false),
    ('high', 'adjective', 4, 1, false, 1, 'reaching a long way up from the ground', 'גבוה', 'A1', 'high', 'העברית משתמשת ב''גבוה'' גם לאנשים וגם לבניינים; באנגלית אדם הוא tall ולא high.', 'גבוה — high · tall', false),
    ('next', 'adjective', 4, 1, false, 1, 'coming immediately after this one in time or order', 'הבא', 'A1', 'high', null, null, false),
    ('include', 'verb', 7, 3, false, 1, 'to have something as one of its parts', 'לכלול', 'B1', 'high', null, null, false),
    ('why', 'adverb', 3, 1, true, 1, 'for what reason', 'למה', 'A1', 'high', 'בעברית ''למה'' פותח שאלה בלי היפוך; דוברי עברית כותבים Why you are late במקום Why are you late.', null, false),
    ('live', 'verb', 4, 1, false, 1, 'to have your home in a place', 'לגור', 'A1', 'high', null, 'לגור — live · reside', false),
    ('live', 'verb', 4, 1, false, 2, 'to be alive; to continue to be alive', 'לחיות', 'A2', 'high', 'העברית משתמשת ב''לגור'' וב''לחיות'' בבירור, אבל live באנגלית מכסה את שתיהן, ולכן דוברי עברית מוסיפים in שלא לצורך במשמעות ''לחיות''.', 'לחיות — live · be alive', false),
    ('end', 'noun', 3, 1, false, 1, 'the last part of something', 'סוף', 'A1', 'high', null, 'סוף — end · finish', false),
    ('end', 'verb', 3, 1, false, 2, 'to stop happening or to finish', 'להסתיים', 'A2', 'high', null, null, false),
    ('world', 'noun', 5, 1, false, 1, 'the earth and all the people who live on it', 'עולם', 'A1', 'high', null, null, false),
    ('week', 'noun', 4, 1, false, 1, 'a period of seven days', 'שבוע', 'A1', 'high', 'week ו-weak נשמעות זהות לדובר עברית ונכתבות באותו אופן בכתיב חופשי, ולכן ההחלפה ביניהן שכיחה.', null, false),
    ('must', 'verb', 4, 1, true, 1, 'used to say that something is necessary', 'חייב', 'A1', 'high', 'דוברי עברית כותבים must to go בהשפעת ''חייב ללכת''; must אינו לוקח to.', null, false),
    ('while', 'conjunction', 5, 1, true, 1, 'during the time that something else is happening', 'בזמן ש', 'A2', 'high', null, null, false),
    ('while', 'conjunction', 5, 1, true, 2, 'used to contrast two different facts', 'ואילו', 'B2', 'medium', 'בעברית ''ואילו'' מופיע רק בתחילת האיבר השני; דוברי עברית ממקמים while בתחילת המשפט וגורמים לקריאה של המשמעות הזמנית.', null, false),
    ('never', 'adverb', 5, 2, true, 1, 'not at any time', 'אף פעם לא', 'A1', 'high', 'העברית דורשת שלילה כפולה (''אף פעם לא''), ולכן דוברי עברית כותבים I never do not eat meat.', null, false),
    ('kind', 'noun', 4, 1, false, 1, 'a group of people or things that are the same in some way', 'סוג', 'A2', 'high', null, 'סוג — kind · type · sort', false),
    ('kind', 'adjective', 4, 1, false, 2, 'caring about other people and wanting to help them', 'אדיב', 'A2', 'high', 'בעברית ''סוג'' ו''אדיב'' אינן קשורות, ולכן דוברי עברית אינם מזהים ש-kind היא אותה מילה בשני התפקידים.', null, false),
    ('play', 'verb', 4, 1, false, 1, 'to take part in a game or to do something for fun', 'לשחק', 'A1', 'high', null, null, false),
    ('play', 'verb', 4, 1, false, 2, 'to make music with an instrument', 'לנגן', 'A2', 'high', 'בעברית ''לשחק'' ו''לנגן'' הן שתי מילים נפרדות, ולכן דוברי עברית מחפשים פועל אחר ל-play the piano ובוחרים ב-sing או ב-make music.', 'לנגן — play (an instrument)', false),
    ('house', 'noun', 5, 1, false, 1, 'a building made for one family to live in', 'בית', 'A1', 'high', 'העברית משתמשת ב''בית'' גם למבנה וגם למקום המגורים; house הוא המבנה בלבד, ולכן I go to house שגוי במקום I go home.', 'בית — house · home', false),
    ('might', 'verb', 5, 1, true, 1, 'used to say that something is possible but not certain', 'עשוי', 'B1', 'high', 'בעברית ''עשוי'' ו''ייתכן'' הם מבנים שונים; דוברי עברית כותבים maybe he will come במקום he might come.', null, false),
    ('home', 'noun', 4, 1, false, 1, 'the place where a person lives and feels they belong', 'בית', 'A1', 'high', null, 'בית — home · house', false),
    ('home', 'adverb', 4, 1, true, 2, 'to or at the place where you live', 'הביתה', 'A1', 'high', 'דוברי עברית כותבים go to home בהשפעת ''ללכת הביתה''; home במשמעות הזאת אינו לוקח to.', null, false),
    ('course', 'noun', 6, 1, false, 1, 'a set of lessons about one subject', 'קורס', 'A2', 'high', null, null, false),
    ('let', 'verb', 3, 1, false, 1, 'to allow somebody to do something', 'להרשות', 'A2', 'high', 'דוברי עברית כותבים let me to help בהשפעת ''להרשות לי לעזור''; let אינו לוקח to לפני הפועל.', null, false),
    ('case', 'noun', 4, 1, false, 1, 'a particular situation or example of something', 'מקרה', 'B1', 'high', null, 'מקרה — case · accident · event', false),
    ('case', 'noun', 4, 1, false, 2, 'a container made to hold and protect something', 'נרתיק', 'B1', 'high', 'העברית מפרידה בין ''מקרה'' ל''נרתיק'', ולכן דוברי עברית אינם מזהים ש-case נושא את שתי המשמעויות באנגלית.', null, false),
    ('system', 'noun', 6, 3, false, 1, 'a set of parts that work together as one whole', 'מערכת', 'B1', 'high', null, null, false),
    ('again', 'adverb', 5, 2, true, 1, 'one more time, after doing it before', 'שוב', 'A1', 'high', null, null, false),
    ('hear', 'verb', 4, 1, false, 1, 'to notice a sound with your ears', 'לשמוע', 'A1', 'high', 'העברית משתמשת ב''לשמוע'' גם ל-hear וגם ל-listen, ולכן דוברי עברית כותבים I hear to music במקום I listen to music.', 'לשמוע — hear · listen', false),
    ('woman', 'noun', 5, 2, false, 1, 'an adult female person', 'אישה', 'A1', 'high', 'המילה ''אישה'' בעברית משמשת גם ל-woman וגם ל-wife, ולכן דוברי עברית כותבים my woman במקום my wife.', 'אישה — woman · wife', false),
    ('family', 'noun', 6, 3, false, 1, 'a group of people who are related to each other', 'משפחה', 'A1', 'high', null, null, false),
    ('book', 'noun', 4, 1, false, 1, 'a set of printed pages held together in a cover', 'ספר', 'A1', 'high', null, null, false),
    ('book', 'verb', 4, 1, false, 2, 'to arrange to have a seat, a room or a table kept for you', 'להזמין', 'B1', 'high', 'המילה ''להזמין'' מכסה book, invite ו-order, ולכן דוברי עברית כותבים I ordered a room במקום I booked a room.', 'להזמין — book · invite · order', false),
    ('around', 'preposition', 6, 2, true, 1, 'on every side of something, or in a circle about it', 'מסביב ל', 'A2', 'high', null, null, false),
    ('around', 'adverb', 6, 2, true, 2, 'a little more or a little less than a number or amount', 'בערך', 'A2', 'high', 'בעברית ''בערך'' עומד לפני המספר כמו באנגלית, אבל דוברי עברית מוסיפים about ו-around יחד (about around ten) בהשפעת ''בערך בסביבות''.', null, false),
    ('during', 'preposition', 6, 2, true, 1, 'all through a period of time, or at some point in it', 'במהלך', 'A2', 'high', 'דוברי עברית משתמשים ב-during לפני משפט שלם (during I was young) כי ''במהלך'' בעברית יכול להוביל פסוקית; during לוקח שם עצם בלבד.', null, false),
    ('big', 'adjective', 3, 1, false, 1, 'large in size or amount', 'גדול', 'A1', 'high', 'העברית משתמשת ב''גדול'' גם למידה וגם לחשיבות; באנגלית a big man הוא בעל גוף, ואילו a great man הוא אדם חשוב.', 'גדול — big · large · great', false),
    ('every', 'determiner', 5, 2, true, 1, 'each one of a group, without leaving any out', 'כל', 'A1', 'high', 'דוברי עברית כותבים every students כי ''כל'' בעברית מופיע גם לפני רבים; every דורש שם עצם ביחיד.', 'כל — every · each · all', false),
    ('question', 'noun', 8, 2, false, 1, 'a sentence that asks somebody for information', 'שאלה', 'A1', 'high', 'דוברי עברית כותבים I have a question to you בהשפעת ''שאלה אליך''; באנגלית זה a question for you.', null, false),
    ('under', 'preposition', 5, 2, true, 1, 'in or to a place below something', 'מתחת ל', 'A1', 'high', null, null, false)
), w as (
  insert into public.words (headword, pos, origin, n_letters, n_syllables, is_function_word)
  select distinct on (headword, pos) headword, pos, 'generated', n_letters, n_syllables, is_function_word
  from incoming
  order by headword, pos
  on conflict (headword, pos) do update set headword = excluded.headword
  returning id, headword, pos
)
insert into public.senses (word_id, sense_index, definition_en, translation_he, cefr_level,
                           translation_confidence, he_interference_note, he_one_to_many_group,
                           generation_run_id, needs_human_review)
select w.id, i.sense_index, i.definition_en, i.translation_he, i.cefr_level,
       i.translation_confidence, i.he_interference_note, i.he_one_to_many_group,
       run.id, i.needs_human_review
from incoming i
join w on w.headword = i.headword and w.pos = i.pos
cross join run
on conflict (word_id, sense_index) do nothing;

-- --------------------------------------------------------------------------
-- batch-2026-08-12.jsonl — 58 of 58 rows pass the gate
-- --------------------------------------------------------------------------
with run as (
  insert into public.generation_runs (model, prompt_version, requested, accepted, rejected, notes)
  values ('claude-opus-5', 'content-agent/2026-08-12', 45, 58, 0, 'batch-2026-08-12.jsonl')
  returning id
), incoming (headword, pos, n_letters, n_syllables, is_function_word, sense_index,
            definition_en, translation_he, cefr_level, translation_confidence,
            he_interference_note, he_one_to_many_group, needs_human_review) as (
  values
    ('few', 'determiner', 3, 1, true, 1, 'a small number of people or things, not many', 'מעטים', 'A1', 'high', 'בעברית ''מעט'' משמש גם לספירים וגם ללא ספירים, ולכן דוברי עברית כותבים few water במקום little water.', null, false),
    ('hand', 'noun', 4, 1, false, 1, 'the part of the body at the end of the arm, with fingers', 'יד', 'A1', 'high', 'בעברית ''יד'' מכסה גם את כף היד וגם את הזרוע, ולכן דוברי עברית כותבים hand במקום arm.', null, false),
    ('state', 'noun', 5, 1, false, 1, 'the condition that somebody or something is in at a certain time', 'מצב', 'B1', 'high', 'בעברית ''מצב'' מכסה state · situation · condition, ולכן דוברי עברית בוחרים situation גם כשהאנגלית דורשת state.', 'מצב', false),
    ('state', 'noun', 5, 1, false, 2, 'one of the areas with its own government that together form a country', 'מדינה', 'B1', 'high', 'state באנגלית אמריקאית הוא יחידה בתוך מדינה ולא country; דוברי עברית מתרגמים ''מדינה'' ל-state וכותבים the state of Israel is in Asia כשכוונתם country.', null, false),
    ('move', 'verb', 4, 1, false, 1, 'to change place or position, or to make something change place', 'לזוז', 'A1', 'high', 'בעברית ''לזוז'' עומד ו''להזיז'' יוצא; move הוא אותה מילה לשניהם, ולכן דוברי עברית מוסיפים מושא מיותר או משמיטים אותו.', null, false),
    ('move', 'verb', 4, 1, false, 2, 'to go to live in a different house or city', 'לעבור דירה', 'A2', 'high', '''לעבור'' בעברית הוא גם move וגם pass; דוברי עברית כותבים we passed to a new house במקום we moved.', 'לעבור', false),
    ('money', 'noun', 5, 2, false, 1, 'what people use to buy things, such as coins and notes', 'כסף', 'A1', 'high', '''כסף'' בעברית הוא גם money וגם המתכת silver, ודוברי עברית כותבים silver כשכוונתם לכסף לתשלום.', 'כסף', false),
    ('however', 'adverb', 7, 3, true, 1, 'used to add something surprising after what was said before', 'עם זאת', 'B1', 'high', 'דוברי עברית משתמשים ב-however כמו ''אבל'' באמצע משפט (I wanted to go however I stayed) במקום לפתוח בו משפט חדש או להפריד בנקודה-פסיק.', null, false),
    ('provide', 'verb', 7, 2, false, 1, 'to give something to somebody that they need', 'לספק', 'B1', 'high', 'בעברית ''לספק משהו למישהו''; דוברי עברית כותבים provide somebody something ומשמיטים את with או את to.', null, false),
    ('name', 'noun', 4, 1, false, 1, 'the word that a person or thing is called', 'שם', 'A1', 'high', '''שם'' בעברית הוא גם name וגם תואר הפועל there, ודוברי עברית מבלבלים ביניהם בתרגום מהיר.', 'שם', false),
    ('read', 'verb', 4, 1, false, 1, 'to look at words and understand what they mean', 'לקרוא', 'A1', 'high', '''לקרוא'' בעברית הוא גם read וגם call; דוברי עברית כותבים I read him on the phone במקום I called him.', 'לקרוא', false),
    ('month', 'noun', 5, 1, false, 1, 'one of the parts that a year is divided into', 'חודש', 'A1', 'high', 'בעברית ''חודשיים'' היא מילה אחת; דוברי עברית מחפשים לה מקבילה וכותבים two month במקום two months.', null, false),
    ('without', 'preposition', 7, 2, true, 1, 'not having or not using something', 'בלי', 'A1', 'high', 'אחרי without בא שם פועל בצורת ing‏; דוברי עברית גוזרים מ''בלי לומר'' וכותבים without to say.', null, false),
    ('information', 'noun', 11, 4, false, 1, 'facts or details about somebody or something', 'מידע', 'A2', 'high', 'information אינו ספיר באנגלית; דוברי עברית גוזרים מ''מידעים'' וכותבים informations או an information.', null, false),
    ('order', 'noun', 5, 2, false, 1, 'the way that things are arranged, one after another', 'סדר', 'A2', 'high', 'בעברית ''בסדר'' פירושו גם fine וגם in order; דוברי עברית עונים in order כשכוונתם okay.', 'סדר', false),
    ('order', 'noun', 5, 2, false, 2, 'a request for food or goods that you want to buy', 'הזמנה', 'A2', 'high', '''הזמנה'' מכסה order (בחנות) · invitation (לאירוע) · reservation (במסעדה), ודוברי עברית משתמשים ב-order לשלושתם.', 'הזמנה', false),
    ('order', 'verb', 5, 2, false, 3, 'to ask for food or goods to be brought to you', 'להזמין', 'A2', 'high', '''להזמין'' מכסה order · invite · reserve; דוברי עברית כותבים I invited a pizza במקום I ordered a pizza.', 'להזמין', false),
    ('government', 'noun', 10, 3, false, 1, 'the group of people who control a country', 'ממשלה', 'B1', 'high', null, null, false),
    ('word', 'noun', 4, 1, false, 1, 'a single unit of language that has a meaning', 'מילה', 'A1', 'high', 'בעברית אין תווית סתמית; דוברי עברית כותבים did not say word במקום did not say a word.', null, false),
    ('issue', 'noun', 5, 2, false, 1, 'an important subject that people discuss or argue about', 'נושא', 'B1', 'high', '''נושא'' בעברית הוא subject · topic · issue; דוברי עברית בוחרים subject גם כשמדובר בנושא שנוי במחלוקת, שבו האנגלית דורשת issue.', 'נושא', false),
    ('issue', 'noun', 5, 2, false, 2, 'one of a series of magazines or newspapers printed at a certain time', 'גיליון', 'B2', 'high', null, null, false),
    ('market', 'noun', 6, 2, false, 1, 'a place where people meet to buy and sell food and goods', 'שוק', 'A2', 'high', '''שוק'' בעברית הוא גם market וגם החלק בגוף; דוברי עברית אומרים in the market במשמעות הכלכלית, אך on the market באנגלית פירושו ''מוצע למכירה''.', 'שוק', false),
    ('pay', 'verb', 3, 1, false, 1, 'to give money for something that you buy or use', 'לשלם', 'A1', 'high', 'בעברית ''לשלם על משהו''; דוברי עברית כותבים pay on the ticket במקום pay for the ticket.', null, false),
    ('build', 'verb', 5, 1, false, 1, 'to make something by putting parts together', 'לבנות', 'A2', 'high', 'צורת העבר של build אינה builded אלא built; דוברי עברית, שאין להם פעלים לא רגולריים, מכלילים את הכלל הרגולרי.', null, false),
    ('service', 'noun', 7, 2, false, 1, 'the help that a shop, hotel or company gives to its customers', 'שירות', 'B1', 'high', 'בעברית ''שירות'' הוא גם service וגם השירות הצבאי; דוברי עברית כותבים I did my service בלי military ומשאירים את הקורא בלי הקשר.', null, false),
    ('against', 'preposition', 7, 2, true, 1, 'opposed to somebody or something', 'נגד', 'A2', 'high', 'בעברית ''נגד'' משמש גם ל-versus במשחקים; דוברי עברית כותבים we played versus them במקום we played against them.', null, false),
    ('second', 'adjective', 6, 2, false, 1, 'coming after the first one', 'שני', 'A1', 'high', 'בעברית ''שני'' הוא גם המספר two וגם הסודר second; דוברי עברית כותבים the two floor במקום the second floor.', null, false),
    ('second', 'noun', 6, 2, false, 2, 'a very short unit of time, much shorter than a minute', 'שנייה', 'A2', 'high', null, 'שנייה', false),
    ('though', 'conjunction', 6, 1, true, 1, 'in spite of the fact that', 'למרות ש', 'B1', 'high', 'though · although · through · thought נראות דומות; דוברי עברית מחליפים ביניהן בכתיבה, ובעיקר בין though לבין through.', null, false),
    ('love', 'verb', 4, 1, false, 1, 'to like somebody or something very much', 'לאהוב', 'A1', 'high', 'באנגלית love משמש גם לחפצים ולפעולות (I love this song); דוברי עברית נמנעים ממנו כי ''אוהב'' חזק יותר בעברית, ומשתמשים ב-like בלבד.', null, false),
    ('love', 'noun', 4, 1, false, 2, 'a very strong feeling of liking somebody', 'אהבה', 'A2', 'high', null, null, false),
    ('result', 'noun', 6, 2, false, 1, 'something that happens because of something else', 'תוצאה', 'A2', 'high', '''תוצאה'' בעברית היא גם result וגם score במשחק; דוברי עברית שואלים what was the result במקום what was the score.', 'תוצאה', false),
    ('away', 'adverb', 4, 2, true, 1, 'to or at a distance from a place or person', 'הרחק', 'A1', 'high', 'בעברית ''רחוק'' משמש גם כתואר וגם כתואר הפועל; דוברי עברית כותבים the school is away far או משמיטים את away ב-far away.', null, false),
    ('example', 'noun', 7, 3, false, 1, 'a thing that shows what a larger group is like', 'דוגמה', 'A2', 'high', 'בעברית ''לדוגמה'' ו''למשל'' זהות; דוברי עברית כותבים for example כשהמשמעות היא such as, ומציבים אותו באמצע רשימה במקום לפניה.', null, false),
    ('happen', 'verb', 6, 2, false, 1, 'to take place, usually without being planned', 'לקרות', 'A1', 'high', 'happen אינו לוקח מושא ישיר ואינו סביל; דוברי עברית כותבים it was happened או they happened an accident.', null, false),
    ('offer', 'verb', 5, 2, false, 1, 'to say that you are ready to give something or do something', 'להציע', 'B1', 'high', '''להציע'' מכסה offer · suggest · propose; דוברי עברית כותבים he offered that we go במקום he suggested that we go.', 'להציע', false),
    ('offer', 'noun', 5, 2, false, 2, 'something that somebody says they will give you', 'הצעה', 'B1', 'high', null, 'הצעה', false),
    ('young', 'adjective', 5, 1, false, 1, 'having lived for only a short time', 'צעיר', 'A1', 'high', 'בעברית ''צעיר'' משמש גם כשם עצם (''הצעירים''); דוברי עברית כותבים the youngs במקום young people או the young.', null, false),
    ('program', 'noun', 7, 2, false, 1, 'a show on television or radio', 'תוכנית', 'A2', 'high', '''תוכנית'' בעברית היא גם program וגם plan; דוברי עברית שואלים what is your program for tomorrow במקום what is your plan.', 'תוכנית', false),
    ('lead', 'verb', 4, 1, false, 1, 'to go in front of people to show them the way', 'להוביל', 'B1', 'high', 'צורת העבר של lead אינה leaded אלא led; דוברי עברית מכלילים את הכלל הרגולרי, ובנוסף מבלבלים בין lead ל-led בהגייה.', null, false),
    ('lead', 'verb', 4, 1, false, 2, 'to be in control of a group, a company or a country', 'לנהל', 'B1', 'high', null, null, false),
    ('buy', 'verb', 3, 1, false, 1, 'to get something by giving money for it', 'לקנות', 'A1', 'high', 'צורת העבר של buy אינה buyed אלא bought; דוברי עברית, שאין להם פעלים לא רגולריים, מכלילים את הכלל הרגולרי.', null, false),
    ('thank', 'verb', 5, 1, false, 1, 'to tell somebody that you are pleased about something they gave or did', 'להודות', 'A1', 'high', '''להודות'' בעברית היא גם thank וגם admit; דוברי עברית כותבים he thanked that he was wrong במקום he admitted.', 'להודות', false),
    ('far', 'adverb', 3, 1, false, 1, 'at or to a great distance', 'רחוק', 'A1', 'high', 'בעברית ''רחוק'' הוא גם תואר וגם תואר הפועל; באנגלית far כמעט אינו משמש כתואר לפני שם עצם, ודוברי עברית כותבים a far city במקום a distant city.', null, false),
    ('today', 'adverb', 5, 2, false, 1, 'on this day', 'היום', 'A1', 'high', '''היום'' בעברית הוא גם today וגם ''the day''; דוברי עברית כותבים the today במקום today.', 'היום', false),
    ('hour', 'noun', 4, 1, false, 1, 'a period of time that is part of a day, longer than a minute', 'שעה', 'A1', 'high', 'hour מתחיל בתנועה בהגייה ולכן לוקח an ולא a; דוברי עברית, שרואים h בכתיב, כותבים a hour.', null, false),
    ('student', 'noun', 7, 2, false, 1, 'a person who is studying at a university or college', 'סטודנט', 'A1', 'high', 'בעברית ''סטודנט'' הוא רק לומד באוניברסיטה ו''תלמיד'' בבית ספר; באנגלית student מכסה את שניהם, ודוברי עברית כותבים pupil גם על סטודנט.', null, false),
    ('face', 'noun', 4, 1, false, 1, 'the front part of the head, with the eyes, nose and mouth', 'פנים', 'A1', 'high', '''פנים'' בעברית היא צורת רבים דקדוקית; דוברי עברית כותבים her faces were red במקום her face was red.', 'פנים', false),
    ('face', 'verb', 4, 1, false, 2, 'to have to deal with a difficult situation', 'להתמודד', 'B2', 'high', 'בעברית ''להתמודד עם'' דורש מילת יחס; דוברי עברית כותבים face with the problem במקום face the problem.', null, false),
    ('less', 'determiner', 4, 1, true, 1, 'a smaller amount of something', 'פחות', 'A2', 'high', '''פחות'' בעברית אחיד; באנגלית less לבלתי ספירים ו-fewer לספירים, ודוברי עברית כותבים less books במקום fewer books.', 'פחות', false),
    ('room', 'noun', 4, 1, false, 1, 'a part of a building with its own walls, floor and door', 'חדר', 'A1', 'high', null, null, false),
    ('room', 'noun', 4, 1, false, 2, 'space that is free for somebody or something', 'מקום', 'B1', 'high', '''מקום'' מכסה room · place · space · seat; דוברי עברית כותבים there is no place in the car במקום there is no room.', 'מקום', false),
    ('until', 'preposition', 5, 2, true, 1, 'up to a certain time and then no longer', 'עד', 'A2', 'high', '''עד'' בעברית משמש גם ל-until וגם ל-by; דוברי עברית כותבים finish it until tomorrow במקום by tomorrow.', 'עד', false),
    ('form', 'noun', 4, 1, false, 1, 'an official paper with spaces where you write information', 'טופס', 'A2', 'high', 'form ו-from נבדלות רק בסדר האותיות; דוברי עברית מחליפים ביניהן בכתיבה יותר מדוברי שפות אחרות.', null, false),
    ('form', 'noun', 4, 1, false, 2, 'the shape of somebody or something', 'צורה', 'B1', 'high', null, 'צורה', false),
    ('head', 'noun', 4, 1, false, 1, 'the part of the body above the neck, with the eyes and mouth', 'ראש', 'A1', 'high', '''ראש'' בעברית מכסה head · top · chief; דוברי עברית כותבים the head of the mountain במקום the top of the mountain.', 'ראש', false),
    ('head', 'noun', 4, 1, false, 2, 'the person who is in control of a group or a company', 'מנהל', 'B1', 'high', null, 'ראש', false),
    ('car', 'noun', 3, 1, false, 1, 'a road vehicle with an engine that carries a small number of people', 'מכונית', 'A1', 'high', 'בעברית ''אוטו'' רווח בדיבור; דוברי עברית כותבים auto באנגלית במקום car.', null, false)
), w as (
  insert into public.words (headword, pos, origin, n_letters, n_syllables, is_function_word)
  select distinct on (headword, pos) headword, pos, 'generated', n_letters, n_syllables, is_function_word
  from incoming
  order by headword, pos
  on conflict (headword, pos) do update set headword = excluded.headword
  returning id, headword, pos
)
insert into public.senses (word_id, sense_index, definition_en, translation_he, cefr_level,
                           translation_confidence, he_interference_note, he_one_to_many_group,
                           generation_run_id, needs_human_review)
select w.id, i.sense_index, i.definition_en, i.translation_he, i.cefr_level,
       i.translation_confidence, i.he_interference_note, i.he_one_to_many_group,
       run.id, i.needs_human_review
from incoming i
join w on w.headword = i.headword and w.pos = i.pos
cross join run
on conflict (word_id, sense_index) do nothing;

commit;
