-- supabase/seed/0005_story_questions.sql
-- GENERATED by scripts/build-story-questions-sql.mjs — do not edit by hand.
--    Regenerate with `npm run build:questions`. Apply exactly like a migration.
--
-- 12 questions · one per story · sources: story-questions-2026-08-25.jsonl
-- Every row was re-gated by lib/core/storyQuestionGate.ts (R-014) before emission.
-- origin is set to generated on every row and is NOT a field of the input (7.6).
-- story_id is resolved by (cefr_level, title_en) — the unique key of public.stories —
--    so re-seeding the stories cannot orphan a question.
-- Apply supabase/migrations/0019_story_questions.sql and seed 0004_stories.sql first.

begin;

insert into public.story_questions (story_id, question_en, answers_he, correct_index, origin) values
    (
      (select id from public.stories
        where cefr_level = 'A1' and title_en = 'The new student'),
      'What did the new student say that she likes to do?',
      array['לקרוא', 'להסתכל', 'לצחוק']::text[],
      0,
      'generated'),
    (
      (select id from public.stories
        where cefr_level = 'A1' and title_en = 'The letter in the book'),
      'Who wrote the letter that was in the book?',
      array['אם', 'אנשים', 'חבר']::text[],
      2,
      'generated'),
    (
      (select id from public.stories
        where cefr_level = 'A1' and title_en = 'The best thing about the job'),
      'What does the mother say is the best thing about her job?',
      array['כסף', 'אנשים', 'משפחה']::text[],
      1,
      'generated'),
    (
      (select id from public.stories
        where cefr_level = 'A2' and title_en = 'The first day at work'),
      'What were the people in the large room talking about?',
      array['עבודה', 'מוצר', 'מערכת']::text[],
      1,
      'generated'),
    (
      (select id from public.stories
        where cefr_level = 'A2' and title_en = 'A day at the market'),
      'What did the woman say that big companies offer?',
      array['מחיר', 'אוכל', 'עבודה']::text[],
      0,
      'generated'),
    (
      (select id from public.stories
        where cefr_level = 'A2' and title_en = 'The report that was late'),
      'What did the friend decide to send without the last figures?',
      array['מכתב', 'תוכנית', 'דוח']::text[],
      2,
      'generated'),
    (
      (select id from public.stories
        where cefr_level = 'B1' and title_en = 'A new policy at school'),
      'Who arranged the meeting and persuaded the other parents?',
      array['סטודנט', 'מנהל', 'הורה']::text[],
      2,
      'generated'),
    (
      (select id from public.stories
        where cefr_level = 'B1' and title_en = 'The value of a pause'),
      'What did the leader try after every question?',
      array['הפסקה', 'תשובה', 'ביטחון עצמי']::text[],
      0,
      'generated'),
    (
      (select id from public.stories
        where cefr_level = 'B1' and title_en = 'What the students deserve'),
      'What did one of the parents suggest to the group?',
      array['קרן', 'תהליך', 'פיתוח']::text[],
      1,
      'generated'),
    (
      (select id from public.stories
        where cefr_level = 'B2' and title_en = 'A crucial assessment'),
      'What did the head of the office urge my colleague to report?',
      array['הערכה', 'נזק', 'אמין']::text[],
      2,
      'generated'),
    (
      (select id from public.stories
        where cefr_level = 'B2' and title_en = 'The barrier no one anticipated'),
      'What did the procedure require every small company to consult?',
      array['שוק', 'משרד', 'הגבלה']::text[],
      1,
      'generated'),
    (
      (select id from public.stories
        where cefr_level = 'B2' and title_en = 'Perspectives on the same outcome'),
      'What did one colleague say the group had neglected?',
      array['רכיב', 'הישג', 'מורכבות']::text[],
      0,
      'generated')
on conflict (story_id) do nothing;

commit;
