-- 0006_amirnet_items.sql — GENERATED by scripts/build-amirnet-items.mjs (T-310).
-- ⛔ Never hand-edit: regenerate with `npm run build:amirnet-items`.
--
-- Source: data/generated/amirnet-items-*.jsonl (commission K-006).
--   manifest amirnet-items-manifest-2026-09-12.json (claude-sonnet-5 · content-2026-08-23-D110)
-- Every row below passed lib/core/amirnetItemGate.ts (rc: amirnetChapterGate.ts) in THIS
-- build, ⛔ not in a reconstruction of it, and carries every column 0024 declares not null.
-- ⛔ Items the build refused are ⛔ NOT here and were ⛔ NOT repaired — see the build output.
--
-- Re-runnable: `on conflict (type, level, stem_en) do nothing` against the unique key
-- 0024_amirnet_items.sql declares. A second apply inserts ⛔ nothing.

begin;

insert into public.amirnet_items
  (type, level, stem_en, passage_en, options_en, correct_index, distractor_reasons,
   explanation_he, level_rationale, vocab_band, source)
values
  ('rs', 1, 'Maria cleaned her room before her friends arrived.', '', array['Maria tidied her room before her friends arrived.', 'Maria''s friends arrived and then she cleaned her room.', 'Maria did not clean her room before her friends came.', 'Maria cleaned her room while her friends were visiting.']::text[],
   0, array['correct — same meaning and same order of events as the source', 'reverses the order of events in the source', 'adds a negation that is not in the source', 'adds an unstated detail — the source says before, not during']::text[], 'אותה משמעות בדיוק — מריה ניקתה את החדר לפני שהחברים הגיעו, בשני הניסוחים.',
   'simple sentence, near-direct paraphrase, common vocabulary ⇒ 1', 1000, 'original'),
  ('rs', 1, 'The teacher canceled the test because of the fire drill.', '', array['The test was canceled due to the fire drill.', 'The fire drill was canceled because of the test.', 'The students canceled the test because of the fire drill.', 'The teacher canceled the test after the fire drill ended.']::text[],
   0, array['correct — same meaning as the source, cause preserved', 'reverses which event was canceled', 'changes who canceled the test — the source says the teacher, not the students', 'adds an unstated detail about timing not in the source']::text[], 'אותה סיבה ואותה תוצאה — המבחן בוטל בגלל תרגיל האש, בשני הניסוחים.',
   'simple sentence, near-direct paraphrase, common vocabulary ⇒ 1', 1000, 'original'),
  ('rs', 2, 'Because the flight was delayed, many passengers missed their connections.', '', array['Many passengers missed their connections because the flight was delayed.', 'Because many passengers missed their connections, the flight was delayed.', 'The flight was delayed although many passengers missed their connections.', 'Many passengers missed their flight because they arrived too late.']::text[],
   0, array['correct — same cause and result as the source', 'reverses the causal relation', 'changes the relation from cause to contrast', 'adds an unstated cause not present in the source']::text[], 'אותו יחס סיבה-תוצאה — הטיסה התעכבה, ולכן הנוסעים איחרו לקשרים.',
   'one subordinate clause, distractor 2 reverses the causal relation ⇒ 2', 2000, 'original'),
  ('rs', 2, 'She lost her job, so she decided to start her own business.', '', array['She decided to start her own business after losing her job.', 'She started her own business, so she lost her job.', 'Although she lost her job, she decided to start her own business.', 'She lost her job because she started her own business too early.']::text[],
   0, array['correct — same cause and result as the source', 'reverses the causal relation', 'changes the relation from consequence to contrast', 'adds an unstated cause and reverses the relation']::text[], 'אותו יחס סיבה-תוצאה — היא איבדה את העבודה, ולכן החליטה לפתוח עסק משלה.',
   'one subordinate clause, distractor 2 reverses the causal relation ⇒ 2', 2000, 'original'),
  ('rs', 3, 'Only after the new manager reviewed every complaint did the company change its refund policy.', '', array['The company changed its refund policy solely once the new manager had reviewed every complaint.', 'The company changed its refund policy after the manager reviewed some of the complaints.', 'The new manager reviewed every complaint after the company changed its refund policy.', 'Every company changes its refund policy once a manager reviews complaints.']::text[],
   0, array['correct — same ''only after'' structure and full scope preserved', 'narrows the scope from every complaint to some', 'reverses the order of events', 'generalizes a single case into a rule about all companies']::text[], 'אותו מבנה only after ואותו היקף — כל תלונה נבדקה, לא רק חלק מהן.',
   '''Only after…did'' structure, distractor 2 narrows the quantifier scope ⇒ 3', 3000, 'original'),
  ('rs', 3, 'The city built the new bridge only after residents had complained for years about the long detour.', '', array['The new bridge was built by the city solely once residents had spent years complaining about the long detour.', 'The city built the new bridge after some residents complained about the detour.', 'Residents complained for years about the detour after the city built the new bridge.', 'Cities usually build new bridges once residents complain about detours.']::text[],
   0, array['correct — same ''only after'' structure and full scope preserved', 'narrows the scope from years of complaints to some residents', 'reverses the order of events', 'generalizes a single case into a rule about cities in general']::text[], 'אותו מבנה only after ואותו היקף — שנים של תלונות, לא רק כמה תושבים.',
   '''Only after'' structure, distractor 2 narrows scope from years to some ⇒ 3', 3000, 'original'),
  ('rs', 4, 'Far from weakening the union''s position, the company''s aggressive tactics ended up uniting workers who had previously disagreed on almost every issue.', '', array['Rather than undermining the union, the company''s tactics actually united workers who had rarely agreed.', 'The company''s aggressive tactics weakened the union''s position, as everyone had expected they would.', 'The union''s position was strengthened because most workers had already agreed on everything.', 'The company decided to soften its tactics in order to finally unite the divided workers.']::text[],
   0, array['correct — preserves the ''far from'' reversal and the main idea', 'reverses the direction stated in the source', 'partially correct but misses the main idea — the workers had previously disagreed', 'changes a core fact — the source says the tactics were aggressive, not softened']::text[], 'אותו רעיון מרכזי, בכיוון ההפוך — הטקטיקות לא החלישו את האיגוד, הן חיזקו אותו.',
   'long sentence with double negation (''far from''), distractor 2 reverses direction, distractor 3 is partially correct but misses the main idea ⇒ 4', 3000, 'original'),
  ('rs', 4, 'Far from discouraging young scientists, the unusually difficult entrance exam attracted more applicants than the university had ever seen before.', '', array['The demanding exam attracted more applicants than the university had ever seen, rather than putting young scientists off.', 'The difficult entrance exam discouraged young scientists, exactly as the university expected.', 'More applicants appeared because the university lowered its entrance requirements.', 'The exam attracted slightly more applicants, although most young scientists found it discouraging.']::text[],
   0, array['correct — preserves the ''far from'' reversal and the main idea', 'reverses the direction stated in the source', 'adds an unstated cause not present in the source', 'partially correct but misses the main idea — the source says far from discouraging']::text[], 'אותו רעיון מרכזי, בכיוון ההפוך — המבחן הקשה לא הרתיע, הוא משך יותר מועמדים.',
   'long sentence with double negation (''far from''), distractor 1 reverses direction, distractor 3 is partially correct but misses the main idea ⇒ 4', 3000, 'original'),
  ('sc', 1, 'My brother was ______ because he lost his keys again.', '', array['worried', 'hungry', 'brave', 'famous']::text[],
   0, array['correct — losing his keys again naturally makes him anxious', 'unrelated to losing keys, nothing in the sentence connects to food', 'unrelated trait, not connected to losing keys', 'unrelated to the situation described']::text[], 'התשובה: worried. איבד את המפתחות שוב — זו סיבה לדאגה, לא לרעב, לאומץ או לתהילה.',
   'short sentence, one blank, common everyday vocabulary, no contrast connective ⇒ 1', 1000, 'original'),
  ('sc', 1, 'The children were ______ when they saw the big balloon at the fair.', '', array['happy', 'tired', 'quiet', 'brave']::text[],
   0, array['correct — seeing something big and fun at a fair naturally makes children happy', 'unrelated emotion; nothing in the sentence suggests tiredness', 'describes behavior, not a fitting emotional reaction here', 'unrelated trait, not connected to seeing a balloon']::text[], 'התשובה: happy. בלון גדול ביריד גורם לשמחה, לא לעייפות, לשקט או לאומץ.',
   'short sentence, one blank, common everyday vocabulary, no contrast connective ⇒ 1', 1000, 'original'),
  ('sc', 2, 'She kept practicing every day ______ she wanted to win the competition.', '', array['because', 'although', 'unless', 'whenever']::text[],
   0, array['correct — gives the reason she kept practicing', 'grammatically fits but reverses the logical relation (concession instead of reason)', 'wrong logical relation; suggests a condition, not a reason', 'grammatically fits but only marks timing, not her motive']::text[], 'התשובה: because. המשפט נותן סיבה לתרגול היומיומי — ניגוד (although) ותנאי (unless) לא מתאימים כאן.',
   'single connective marking reason (because), vocabulary within the 2,000-word range ⇒ 2', 2000, 'original'),
  ('sc', 2, 'The bridge was closed for repairs, ______ we had to take a different road.', '', array['so', 'because', 'but', 'unless']::text[],
   0, array['correct — marks the result of the closure', 'grammatically fits but reverses cause and effect', 'grammatically fits but signals contrast, not a result', 'wrong logical relation; suggests a condition, not a result']::text[], 'התשובה: so. הגשר נסגר ולכן היה צריך לקחת כביש אחר — זו תוצאה, לא סיבה (because) או ניגוד (but).',
   'single connective marking result (so), vocabulary within the 2,000-word range ⇒ 2', 2000, 'original'),
  ('sc', 3, '______ repeated delays in shipping, the company still managed to deliver every order on time last month.', '', array['despite', 'given', 'throughout', 'regarding']::text[],
   0, array['correct — creates the contrast between the delays and the on-time delivery', 'plausible preposition but treats the delays as a reason rather than an obstacle', 'suggests the delays continued the whole time, not a contrast with the outcome', 'does not fit a contrast relation at all']::text[], 'התשובה: despite. יש ניגוד בין העיכובים למשלוח בזמן — given הופך את זה לסיבה, לא לניגוד.',
   'contrast preposition (despite), academic-range vocabulary, distractor ''given'' plausible only on a partial reading ⇒ 3', 3000, 'original'),
  ('sc', 3, 'The new restaurant received excellent reviews online, ______ several regular customers complained privately about slow service.', '', array['although', 'besides', 'therefore', 'consequently']::text[],
   0, array['correct — sets the online praise against the private complaints', 'wrong relation; adds a further point rather than contrasting', 'wrong relation; implies a conclusion, not a contrast', 'wrong relation; implies cause and effect, not contrast']::text[], 'התשובה: although. הביקורות המצוינות מנוגדות לתלונות הפרטיות — besides ו-therefore לא יוצרים ניגוד.',
   'concession connective (although), academic-range vocabulary, two distractors plausible only on a partial reading ⇒ 3', 3000, 'original'),
  ('sc', 4, 'Although the reviewer''s comments were almost entirely ______, the publisher''s marketing team quoted them as ______ on the book''s cover.', '', array['critical / glowing', 'mixed / balanced', 'glowing / critical', 'detailed / general']::text[],
   0, array['correct — the negative comments are misleadingly presented as positive praise', 'grammatically fine pair but does not create the contrast ''Although'' requires', 'reverses the correct pair; only careful reading rules it out', 'grammatically fine pair but not an evaluative contrast that fits the sentence']::text[], 'התשובה: critical / glowing. הביקורת השלילית הוצגה כאילו היא חיובית — בדיוק מה ש-Although דורש.',
   'two mutually dependent blanks; the first blank''s polarity fixes what ''Although'' requires the second to contradict; top of the academic vocabulary range ⇒ 4', 3000, 'original'),
  ('sc', 4, 'Although the negotiators'' opening offer sounded almost entirely ______, both sides privately treated it as ______ once the real talks began.', '', array['generous / tentative', 'flexible / decisive', 'tentative / generous', 'written / verbal']::text[],
   0, array['correct — an offer that sounds generous is nonetheless treated only as tentative, not final', 'grammatically fine pair but does not create the required contrast', 'reverses the correct pair; only careful reading rules it out', 'grammatically fine pair but unrelated to the evaluative contrast the sentence needs']::text[], 'התשובה: generous / tentative. ההצעה נשמעה נדיבה אך טופלה כזמנית בלבד — הניגוד הוא הלב של המשפט.',
   'two mutually dependent blanks; distractor 3 swaps the correct pair to test careful reading; unconstrained vocabulary range ⇒ 4', 3000, 'original')
on conflict (type, level, stem_en) do nothing;

commit;
