/**
 * The summary half of D-035 ⓑ: "the 806 sentences were passed through the fixed gate
 * again, and the reject count is known and reported."
 *
 * Pure on purpose. The number this file produces is the release condition of a blocked
 * task, so it is produced by tested code — ⛔ not by a console.log in a script nobody
 * asserts against. The script that reads the files lives in scripts/measure-gate.mjs.
 */

export interface GateOutcome {
  readonly file: string;
  /** 1-based line number inside `file`, so the reader can open the jsonl and look. */
  readonly line: number;
  readonly headword: string;
  readonly ok: boolean;
  readonly reasons: readonly string[];
}

export interface GatedCounts {
  /** Every example sentence handed to the gate, on passing AND rejected rows alike. */
  readonly sentencesGated: number;
  readonly itemStemsGated: number;
}

export interface ReasonCount {
  readonly reason: string;
  readonly count: number;
}

export interface GateReport {
  readonly rowsRead: number;
  readonly rowsPassed: number;
  readonly rowsRejected: number;
  readonly sentencesGated: number;
  readonly itemStemsGated: number;
  readonly reasonHistogram: readonly ReasonCount[];
  readonly rejectedRows: readonly GateOutcome[];
}

/**
 * gateSense() writes reasons for a HUMAN reading one row: "item 3: leaks the answer",
 * "example neutral: level drift on \"kettle\"". Counted verbatim, a single systematic
 * fault would print as forty distinct one-line entries and the shape of the failure
 * would be invisible. The family strips the index and the quoted payload, and nothing
 * else — ⛔ it does not classify, and it does not know the gate's rule list.
 */
export function reasonFamily(reason: string): string {
  const generalized = reason
    .replace(/^example (supportive|neutral)\b/, 'example')
    .replace(/^item \d+\b/, 'item');
  // `?? generalized` is unreachable in practice — String.split always yields index 0 —
  // and exists only because tsconfig sets noUncheckedIndexedAccess. ⛔ no `!` assertion.
  const head = generalized.split('"')[0] ?? generalized;
  const trimmed = head.replace(/\s+on\s*$/, '').replace(/[\s:]+$/, '').trim();
  return trimmed === '' ? generalized.trim() : trimmed;
}

export function summarizeGate(
  outcomes: readonly GateOutcome[],
  counts: GatedCounts,
): GateReport {
  const rejectedRows = outcomes.filter((row) => !row.ok);
  const tally = new Map<string, number>();
  for (const row of rejectedRows) {
    for (const reason of row.reasons) {
      const family = reasonFamily(reason);
      tally.set(family, (tally.get(family) ?? 0) + 1);
    }
  }
  // Count descending, then name ascending: a Map preserves insertion order, which is
  // input order, which would make the committed report churn on every content tick.
  const reasonHistogram = [...tally.entries()]
    .map(([reason, count]) => ({ reason, count }))
    .sort((a, b) => (b.count - a.count) || a.reason.localeCompare(b.reason));

  return {
    rowsRead: outcomes.length,
    rowsPassed: outcomes.length - rejectedRows.length,
    rowsRejected: rejectedRows.length,
    sentencesGated: counts.sentencesGated,
    itemStemsGated: counts.itemStemsGated,
    reasonHistogram,
    rejectedRows,
  };
}

export function formatGateReport(report: GateReport): string {
  const lines: string[] = [
    '# Gate re-check — D-035 ⓑ',
    '',
    '⛔ GENERATED by scripts/measure-gate.mjs — do not edit by hand.',
    'Regenerate with `npm run measure:gate`.',
    '',
    `- ${report.rowsRead} rows read`,
    `- ${report.sentencesGated} example sentences re-gated`,
    `- ${report.itemStemsGated} item stems re-gated`,
    `- ${report.rowsPassed} rows passed`,
    `- ${report.rowsRejected} rows rejected`,
    '',
    '## Rejections by family',
    '',
  ];
  if (report.reasonHistogram.length === 0) {
    lines.push('None. ⛔ Zero rejections is a measurement, not an absent measurement.');
  } else {
    for (const entry of report.reasonHistogram) lines.push(`- ${entry.count} × ${entry.reason}`);
  }
  lines.push('', '## Rejected rows', '');
  if (report.rejectedRows.length === 0) {
    lines.push('None.');
  } else {
    for (const row of report.rejectedRows) {
      lines.push(`- ${row.file}:${row.line} — "${row.headword}" — ${row.reasons.join(' · ')}`);
    }
  }
  lines.push('');
  return lines.join('\n');
}
