/**
 * D-058 — כמה כותרות **פנויות-עם-תווית** נשארו בכל רמה. טהור: הקורא קורא את הקבצים.
 *
 * ⛔ האוכלוסייה היא **הפרופיל** (CEFR-J 1.5 ∪ Octanove 1.0), ⛔ ולא טבלת `words`.
 * שורה ב-`words` נוצרת אך ורק מרשומת אצווה (scripts/build-ingest-sql.mjs:192),
 * ו-scripts/build-word-levels-sql.mjs מצהיר «UPDATE only … never creates a word»
 * ⇒ «מתויגת וטרם נכתבה» היא הקבוצה הריקה בהגדרה, ומספר שנספר משם הוא 0 לנצח.
 *
 * ⛔ «פנויה» ⛔ אינה «מתויגת»: כותרת מחוץ לרשימת ההיתר (NGSL v1.2) אסורה לכתיבה.
 * נמדד 2026-08-21: 8,843 מתויגות מול 3,293 שגם מותרות — פי 2.7. ⇒ free = allowed − authored.
 *
 * ⛔ אינו נוגע ב-senses.cefr_level. D-034: השתיים חלוקות על 125 מתוך 343 שורות, ושתיהן נכונות.
 */
import { BAND_ORDER, type CefrBand } from './cefrLevels';
import { normalizeEnglish } from './lexicon';

export interface HeadroomInput {
  readonly labelled: ReadonlyMap<string, CefrBand>;
  readonly allowed: Iterable<string>;
  readonly authored: Iterable<string>;
}

export interface BandHeadroom {
  readonly band: CefrBand;
  readonly labelled: number;
  readonly allowed: number;
  readonly authored: number;
  readonly free: number;
  readonly offLimits: number;
}

export interface HeadroomTotals {
  readonly labelled: number;
  readonly allowed: number;
  readonly authored: number;
  readonly free: number;
  readonly offLimits: number;
}

export interface HeadroomReport {
  readonly bands: readonly BandHeadroom[];
  readonly totals: HeadroomTotals;
  readonly authoredUnlabelled: number;
  readonly authoredOffLimits: number;
}

/** Set ולא מערך: רשימת ההיתר נמדדה 24,913 שורות, וחיפוש ליניארי בה על 8,843 למות הוא O(n·m). */
function normalizedSet(values: Iterable<string>): Set<string> {
  const out = new Set<string>();
  for (const v of values) {
    const key = normalizeEnglish(v);
    if (key !== '') out.add(key);
  }
  return out;
}

export function measureHeadroom(input: HeadroomInput): HeadroomReport {
  const allowed = normalizedSet(input.allowed);
  const authored = normalizedSet(input.authored);

  // מאותחל מ-BAND_ORDER ⛔ ולא מהנתונים: רמה בלי ולו כותרת אחת חייבת להופיע בדוח
  // כשורת אפס. C1/C2 הן בדיוק המקרה הזה, והן הרמות שבגללן D-058 נכתבה.
  const counters = new Map<CefrBand, { labelled: number; allowed: number; authored: number }>();
  for (const band of BAND_ORDER) counters.set(band, { labelled: 0, allowed: 0, authored: 0 });

  for (const [rawLemma, band] of input.labelled) {
    const lemma = normalizeEnglish(rawLemma);
    if (lemma === '') continue;
    const c = counters.get(band);
    if (c === undefined) continue; // תווית שאינה אחת מהשש — ⛔ אינה נספרת בשקט תחת אחרת
    c.labelled += 1;
    if (!allowed.has(lemma)) continue;
    c.allowed += 1;
    if (authored.has(lemma)) c.authored += 1;
  }

  const bands: BandHeadroom[] = BAND_ORDER.map((band) => {
    const c = counters.get(band) ?? { labelled: 0, allowed: 0, authored: 0 };
    return {
      band,
      labelled: c.labelled,
      allowed: c.allowed,
      authored: c.authored,
      free: c.allowed - c.authored,
      offLimits: c.labelled - c.allowed,
    };
  });

  const totals: HeadroomTotals = bands.reduce(
    (acc, b) => ({
      labelled: acc.labelled + b.labelled,
      allowed: acc.allowed + b.allowed,
      authored: acc.authored + b.authored,
      free: acc.free + b.free,
      offLimits: acc.offLimits + b.offLimits,
    }),
    { labelled: 0, allowed: 0, authored: 0, free: 0, offLimits: 0 },
  );

  // שני מוני הכשל של D-058. הם ⛔ אינם נסכמים לתוך totals: כותרת שאין לה תווית
  // אינה שייכת לאף רמה, וסכימתה לתוך רמה כלשהי היא בדיוק פער 3 שהם מודדים.
  let authoredUnlabelled = 0;
  let authoredOffLimits = 0;
  const labelledKeys = new Set<string>();
  for (const rawLemma of input.labelled.keys()) {
    const key = normalizeEnglish(rawLemma);
    if (key !== '') labelledKeys.add(key);
  }
  for (const lemma of authored) {
    if (!labelledKeys.has(lemma)) authoredUnlabelled += 1;
    else if (!allowed.has(lemma)) authoredOffLimits += 1;
  }

  return { bands, totals, authoredUnlabelled, authoredOffLimits };
}

/**
 * `generatedAt` מוזרק ⛔ ואינו נלקח כאן: `Date` בקובץ ב-/lib/core מפיל את
 * `npm run check:core`, וזו בדיוק הסיבה שהשער קיים.
 */
export function renderHeadroomMarkdown(
  report: HeadroomReport,
  provenance: readonly string[],
  generatedAt: string,
): string {
  const lines: string[] = [
    '<!-- GENERATED by scripts/measure-level-headroom.mjs (T-114). ⛔ Do not hand-edit. -->',
    '',
    '# כמה כותרות פנויות-עם-תווית נשארו בכל רמה',
    '',
    `נמדד: ${generatedAt}`,
    '',
    '⛔ האוכלוסייה היא **הפרופיל** (`cefr_profile_band`: CEFR-J 1.5 ∪ Octanove 1.0),',
    '⛔ ולא טבלת `words` — שורה שם נוצרת אך ורק אחרי שנכתבה לה משמעות, ולכן',
    '"מתויגת וטרם נכתבה" היא הקבוצה הריקה בהגדרה.',
    '',
    '⛔ **`free` הוא המספר היחיד שסוכן התוכן רשאי לתכנן לפיו** (D-058 סעיף 1):',
    'כותרת מתויגת שאינה ברשימת ההיתר (NGSL v1.2) אסורה לכתיבה ונספרת ב-`offLimits`.',
    '',
    '| רמה | מתויגות | מותרות | נכתבו | **פנויות** | מחוץ להיתר |',
    '|---|---|---|---|---|---|',
  ];
  for (const b of report.bands) {
    lines.push(
      `| ${b.band} | ${b.labelled} | ${b.allowed} | ${b.authored} | **${b.free}** | ${b.offLimits} |`,
    );
  }
  const t = report.totals;
  lines.push(
    `| **סה"כ** | ${t.labelled} | ${t.allowed} | ${t.authored} | **${t.free}** | ${t.offLimits} |`,
    '',
    '## שני מוני הכשל של D-058',
    '',
    `- כותרות שנכתבו ואין להן תווית פרופיל (פער 3 — עבודה שנפלה לרצפה): **${report.authoredUnlabelled}**`,
    `- כותרות שנכתבו, מתויגות, ⛔ אך מחוץ לרשימת ההיתר: **${report.authoredOffLimits}**`,
    '',
    '## מקורות',
    '',
    ...provenance.map((p) => `- ${p}`),
    '',
  );
  return lines.join('\n');
}
