import { execFileSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

import { parseVocabCsv, toVocabSql } from './build-amirnet-vocab-sql.mjs';

/**
 * `T-323` — the 6,715 derived rows stop being a CSV one script reads and become SQL.
 *
 * Two halves, deliberately. The PURE half asserts `toVocabSql` on hand-built rows, so the
 * escaping and the `41 § 6` gates are pinned to examples a reader can check by eye. The
 * END-TO-END half runs the generator with `SEED_OUT_DIR` pointed at a throwaway directory
 * and then asserts the committed seed is byte-identical — the same shape, and the same
 * measured reason, as `build-amirnet-items.test.ts` (`F-048ⓑ`): `npm test` ⛔ never dirties
 * a git-managed file, and a seed that has fallen behind `data/generated/` is a RED TEST,
 * ⛔ not a silence that repairs itself on the next agent's run.
 */
const SQL = 'supabase/seed/0007_amirnet_vocab.sql';
const CSV = join('data', 'generated', 'amirnet-vocab.csv');

const OUT_DIR = mkdtempSync(join(tmpdir(), 'seed-amirnet-vocab-'));
const FRESH = join(OUT_DIR, '0007_amirnet_vocab.sql');

function run(env: Record<string, string> = {}): string {
  return execFileSync('node', ['scripts/build-amirnet-vocab-sql.mjs'], {
    encoding: 'utf8',
    env: { ...process.env, SEED_OUT_DIR: OUT_DIR, ...env },
  });
}

const stdout = run();
const sql = (): string => readFileSync(FRESH, 'utf8');

const ROW = {
  headword: 'abandon',
  pos: 'verb',
  cefr: 'B1',
  tier: 2,
  tier_name: 'ליבה מורחבת',
  amirnet_level: '2-3',
  is_connector: false,
  source: 'CEFR-J v1.5',
};

describe('toVocabSql', () => {
  it('drops A1 and C2 before they ever reach SQL (41 § 6, steps 3-4)', () => {
    const out = toVocabSql([ROW]);
    expect(out).toContain("('abandon'");
    expect(out).not.toMatch(/'A1'|'C2'/);
  });

  it('escapes an apostrophe instead of breaking the statement', () => {
    const out = toVocabSql([
      { ...ROW, headword: "o'clock", pos: 'noun', cefr: 'A2', tier: 1, tier_name: 'ליבה', amirnet_level: '1-2' },
    ]);
    expect(out).toContain("('o''clock'");
  });

  it('is idempotent on re-apply — a second load changes nothing', () => {
    expect(toVocabSql([])).toContain('on conflict (headword) do nothing');
  });

  it('⛔ REFUSES a band the table cannot take — ⛔ it never silently drops it', () => {
    // `amirnet_vocab_cefr_check` would refuse the row at the database. Emitting it and
    // letting the load fail 6,000 rows later is ⛔ not a gate; refusing here is.
    expect(() => toVocabSql([{ ...ROW, cefr: 'C2' }])).toThrow(/C2/);
    expect(() => toVocabSql([{ ...ROW, cefr: 'A1', tier: 1 }])).toThrow(/A1/);
  });

  it('⛔ REFUSES a tier that does not match its Hebrew name (amirnet_vocab_tier_name_pairing)', () => {
    expect(() => toVocabSql([{ ...ROW, tier: 1 }])).toThrow(/ליבה מורחבת/);
  });

  it('writes the boolean as SQL, ⛔ not as the CSV\'s empty string', () => {
    expect(toVocabSql([{ ...ROW, is_connector: true }])).toContain('true');
    expect(toVocabSql([ROW])).toContain('false');
  });
});

describe('build-amirnet-vocab-sql — the emitter (T-323)', () => {
  it('writes only where SEED_OUT_DIR points — `npm test` ⛔ never dirties the repo (F-048ⓑ)', () => {
    expect(existsSync(FRESH), `${FRESH} — generator ignored SEED_OUT_DIR`).toBe(true);
  });

  it('emits every derived row — the count is a MEASUREMENT of the CSV, ⛔ not a literal', () => {
    const rows = readFileSync(CSV, 'utf8').split(/\r?\n/).filter((l) => l.trim() !== '').length - 1;
    expect(rows).toBeGreaterThan(0);
    expect(stdout).toContain(`${rows} rows`);
    // One `values` tuple per row: every line that opens with `(` and a quoted headword.
    expect(sql().split('\n').filter((l) => /^\s{4}\('/.test(l))).toHaveLength(rows);
  });

  it('carries the four tier names of `41 § 6` step 5, and ⛔ no fifth', () => {
    const names = new Set([...sql().matchAll(/, '(ליבה|ליבה מורחבת|הרחבה אקדמית|רמת פטור)'/g)].map((m) => m[1]));
    expect(names).toEqual(new Set(['ליבה', 'ליבה מורחבת', 'הרחבה אקדמית', 'רמת פטור']));
  });

  it('declares itself generated — `supabase/seed/**` is ⛔ never hand-edited (HARD INVARIANTS)', () => {
    expect(sql()).toContain('⛔ GENERATED by scripts/build-amirnet-vocab-sql.mjs');
    expect(sql()).toContain('npm run build:amirnet-vocab-sql');
  });

  it('a SECOND run over the same input is byte-identical (deterministic, ⛔ not incidentally stable)', () => {
    const before = sql();
    run();
    expect(sql()).toBe(before);
  });

  it('the COMMITTED seed is byte-identical to a fresh build — staleness is a red test', () => {
    expect(existsSync(SQL), `${SQL} — run \`npm run build:amirnet-vocab-sql\``).toBe(true);
    expect(readFileSync(SQL, 'utf8')).toBe(sql());
  });
});

/**
 * ⛔ The declaration file is hand-written (`build-amirnet-vocab-sql.d.mts`), so it can
 * drift from the module. The blocks above catch a changed BEHAVIOUR; this one catches a
 * changed SHAPE — the same pairing `next-cycle-id.test.ts` uses.
 */
describe('the hand-written declaration file', () => {
  it('declares exactly the names the module exports', async () => {
    const mod = await import('./build-amirnet-vocab-sql.mjs');
    const declared = [
      ...readFileSync('scripts/build-amirnet-vocab-sql.d.mts', 'utf8').matchAll(
        /export declare (?:const|function)\s+([A-Za-z_$][\w$]*)/g,
      ),
    ].map((m) => m[1]);
    expect([...declared].sort()).toEqual(Object.keys(mod).sort());
  });

  it('parseVocabCsv reads the CSV\'s empty cell as false, ⛔ not as a truthy string', () => {
    const rows = parseVocabCsv(
      'headword,pos,cefr,tier,tier_name,amirnet_level,is_connector,source\n' +
        'and,conjunction,A2,1,\u05dc\u05d9\u05d1\u05d4,1-2,true,CEFR-J v1.5\n' +
        'ability,noun,A2,1,\u05dc\u05d9\u05d1\u05d4,1-2,,CEFR-J v1.5\n',
    );
    expect(rows.map((r) => r.is_connector)).toEqual([true, false]);
    expect(rows[0]?.tier).toBe(1);
  });
});
