import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

const OUT_DIR = mkdtempSync(join(tmpdir(), 'plan-tables-'));
const FRESH = join(OUT_DIR, 'plan-tables.md');
const stdout = execFileSync('node', ['scripts/measure-plan-tables.mjs'], {
  encoding: 'utf8',
  env: { ...process.env, PLAN_TABLES_OUT: FRESH },
});

/**
 * A RATCHET, ⛔ not an assertion of correctness — with one half now closed.
 *
 * ⚠️ C-0152 set both ceilings on the belief that both registers belong to other agents.
 * Half of that is wrong, and it is checkable in one line: `plan/50-tasks.md:3` declares
 * `⟦OWNER: Dev · PM מוסיף פריטים חדשים בלבד⟧`, so the task register is **this** agent's
 * to repair; only `plan/60-findings.md:3` (`⟦OWNER: Critic כותב · Dev מסמן טופל⟧`) is
 * someone else's prose. C-0156 repaired all six task rows accordingly ⇒ the task ceiling
 * is **0** and is now a real assertion: any new task row that does not split into its 8
 * declared columns fails here, in the register the Dev owns and writes every tick.
 *
 * The findings ceiling stays a ratchet at the C-0152 measurement, because demanding zero
 * there would redden the tree on the Critic's prose — the exact shape of F-030. Repairs
 * lower it; ⛔ nothing raises it silently.
 */
const MALFORMED_TASKS_CEILING = 0;
const MALFORMED_FINDINGS_CEILING = 19;

const numberAfter = (label: string): number => {
  const m = new RegExp(`${label}: \\d+ rows, (\\d+) malformed`).exec(stdout);
  if (m?.[1] === undefined) throw new Error(`no "${label}" line in stdout:\n${stdout}`);
  return Number(m[1]);
};

describe('scripts/measure-plan-tables.mjs', () => {
  it('reports on both registers', () => {
    expect(stdout).toMatch(/^tasks: \d+ rows, \d+ malformed$/m);
    expect(stdout).toMatch(/^findings: \d+ rows, \d+ malformed$/m);
  });

  it('never lets the malformed-row count grow', () => {
    expect(numberAfter('tasks')).toBeLessThanOrEqual(MALFORMED_TASKS_CEILING);
    expect(numberAfter('findings')).toBeLessThanOrEqual(MALFORMED_FINDINGS_CEILING);
  });

  it('holds every ⛔ cell to a blocker that has not already lifted', () => {
    // ⚠️ C-0157 replaced the previous assertion, which pinned the live defect
    // (`stale blockers: T-066 cites F-020 (closed)`) and told the next agent to DELETE
    // this test once T-066's ⛔ cell was rewritten. Deleting it would have retired the
    // only mechanised copy of F-050's rule the moment it first paid out, so the
    // assertion was inverted instead of dropped. This is STRICTLY STRONGER than the
    // old one — it fails on T-066 citing a closed F-020 exactly as before, and also on
    // any OTHER row that starts citing a closed finding — ⛔ and it is not the weakened
    // regex the old comment warned about, because "none" is the only string it accepts.
    expect(stdout).toContain('stale blockers: none');
  });

  it('holds every ⛔ cell to a task blocker that has not already been delivered', () => {
    // C-0158's half of the same rule. Eight ⬜ rows were rewritten to ⛔ this tick, and
    // three of them declare `חסם: T-043` — a human action. The day Roy lands the source
    // files and T-043 flips to ✅, those three go stale in exactly the silent way T-066
    // did for ten cycles. Mutation-checked this tick: marking T-043 ✅ turns this red with
    // `T-007 waits on T-043 (done)` plus two siblings. "none" is the only string it takes.
    expect(stdout).toContain('stale task blockers: none');
  });

  it('writes a report that names the malformed rows', () => {
    const fresh = readFileSync(FRESH, 'utf8');
    expect(fresh).toContain('GENERATED by scripts/measure-plan-tables.mjs');
    // ⚠️ Was `T-042` until C-0156 repaired it. The naming behaviour is what this test
    // guards, so it moves to a row that is still malformed — `F-046` carries 5 cells of
    // the 8 its header declares — ⛔ and is not weakened to a regex that passes on none.
    expect(fresh).toContain('`F-046`');
  });

  it('leaves the committed report identical to a fresh run', () => {
    // The committed docs/plan-tables.md is evidence, ⛔ not decoration: if it drifts from
    // what the script produces, the next agent reads a stale answer and trusts it.
    expect(readFileSync(join('docs', 'plan-tables.md'), 'utf8')).toBe(readFileSync(FRESH, 'utf8'));
  });
});
