import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

const OUT_DIR = mkdtempSync(join(tmpdir(), 'plan-tables-'));
const FRESH = join(OUT_DIR, 'plan-tables.md');
const stdout = execFileSync('node', ['scripts/measure-plan-tables.mjs'], {
  encoding: 'utf8',
  env: { ...process.env, PLAN_TABLES_OUT: FRESH },
});

/**
 * A RATCHET, ⛔ not an assertion of correctness. `plan/50-tasks.md` belongs to the PM and
 * `plan/60-findings.md` to the Critic; a Dev test that demanded zero malformed rows would
 * redden the tree on someone else's prose and hand the Critic a red suite that means
 * nothing — the exact shape of F-030. So the ceilings are the measured counts of C-0152,
 * and only a WORSENING fails. Repairs lower the ceiling; ⛔ nothing raises it silently.
 */
const MALFORMED_TASKS_CEILING = 6;
const MALFORMED_FINDINGS_CEILING = 19;

const numberAfter = (label: string): number => {
  const m = new RegExp(`${label}: \\d+ rows, (\\d+) malformed`).exec(stdout);
  if (m?.[1] === undefined) throw new Error(`no "${label}" line in stdout:\n${stdout}`);
  return Number(m[1]);
};

describe('scripts/measure-plan-tables.mjs', () => {
  it('reports on both registers', () => {
    expect(stdout).toMatch(/^tasks: \d+ rows, \d+ malformed$/m);
    expect(stdout).toMatch(/^findings: \d+ rows, \d+ malformed$/m);
  });

  it('never lets the malformed-row count grow', () => {
    expect(numberAfter('tasks')).toBeLessThanOrEqual(MALFORMED_TASKS_CEILING);
    expect(numberAfter('findings')).toBeLessThanOrEqual(MALFORMED_FINDINGS_CEILING);
  });

  it('detects the live stale blocker — T-066 is blocked by a closed F-020', () => {
    // ⚠️ This assertion is expected to STOP being true, and that is the success case:
    // when the PM rewrites T-066's ⛔ cell, delete this test in the same commit and say
    // so in the journal. ⛔ Do not weaken it to a regex that also passes on "none".
    expect(stdout).toContain('stale blockers: T-066 cites F-020 (closed)');
  });

  it('writes a report that names the malformed rows', () => {
    const fresh = readFileSync(FRESH, 'utf8');
    expect(fresh).toContain('GENERATED by scripts/measure-plan-tables.mjs');
    expect(fresh).toContain('`T-042`');
  });

  it('leaves the committed report identical to a fresh run', () => {
    // The committed docs/plan-tables.md is evidence, ⛔ not decoration: if it drifts from
    // what the script produces, the next agent reads a stale answer and trusts it.
    expect(readFileSync(join('docs', 'plan-tables.md'), 'utf8')).toBe(readFileSync(FRESH, 'utf8'));
  });
});
