-- 0040_ngsl_frequency.sql — NGSL v1.2 as a table: the frequency backbone (T-007 · 10-pedagogy
-- 1.3.1 S1 · T-012 · F-005).
--
-- Applied through the Supabase MCP connector (`apply_migration`) by the DEV tick that builds
-- T-007 (C-0829), and ⛔ never left for Roy (D-163). Rows: supabase/seed/0008_ngsl_frequency.sql,
-- generated by scripts/build-ngsl-sql.mjs from data/ngsl-1.2.csv.
--
-- ⛔ **WHY A TABLE, ⛔ AND ⛔ NOT ROWS IN `words`.** `words.pos` is `not null` and its key is
-- `(headword, pos)`; NGSL carries ⛔ no part of speech, so writing its lemmas into `words`
-- would mean inventing one per row (R-010). ⇒ the whole list lives here, and `words`
-- receives only `ngsl_rank`, by headword — the column 0002 created for exactly this and which
-- held 0 of 1,559 values on the live database (measured C-0829).
--
-- ⛔ **Not the learner's vocabulary state** (R-020): zero foreign key to `word_progress`.
-- ⛔ **Client reads only** — `grant select`, ⛔ no insert · update · delete.
--
-- Down (manual — an applied migration is ⛔ not reversible by a commit, `RULES § 0.22`):
--   update public.study_level_cursor set last_ngsl_rank = null;
--   update public.words set ngsl_rank = null;
--   drop table if exists public.ngsl_frequency;
--
-- Idempotent: `create table if not exists`, constraints named and added inside `do $$`
-- (C-0032 — a `check` inside `create table` is skipped wholesale when the table exists).

begin;

create table if not exists public.ngsl_frequency (
  rank       int          primary key,
  headword   text         not null,
  sfi        numeric(5,2) not null,
  created_at timestamptz  not null default now()
);

do $$
begin
  -- T-012 · F-005 — v1.2 is 2,809 lemmas; 2,801 is the early list from R-004's bad domain.
  if not exists (select 1 from pg_constraint where conname = 'ngsl_frequency_rank_check') then
    alter table public.ngsl_frequency
      add constraint ngsl_frequency_rank_check check (rank between 1 and 2809);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'ngsl_frequency_headword_check') then
    alter table public.ngsl_frequency
      add constraint ngsl_frequency_headword_check
      check (length(headword) > 0 and headword = btrim(headword));
  end if;

  if not exists (select 1 from pg_constraint where conname = 'ngsl_frequency_sfi_check') then
    alter table public.ngsl_frequency
      add constraint ngsl_frequency_sfi_check check (sfi > 0 and sfi < 100);
  end if;
end $$;

-- The backfill in the seed joins on lower(headword); this makes that join an index lookup
-- and makes a case-only duplicate unwritable.
create unique index if not exists ngsl_frequency_headword_lower_idx
  on public.ngsl_frequency (lower(headword));

comment on table public.ngsl_frequency is
  'T-007 — NGSL v1.2 (Browne, Culligan & Phillips · CC BY-SA 4.0), 2,809 lemmas, from
   newgeneralservicelist.com only (R-004). The source of words.ngsl_rank. ⛔ Not the
   learner''s vocabulary state (R-020).';
comment on column public.ngsl_frequency.sfi is
  'Standard Frequency Index as published with the list. ⛔ Not a CEFR level and ⛔ not a score.';

alter table public.ngsl_frequency enable row level security;

drop policy if exists "ngsl_frequency_select_all" on public.ngsl_frequency;
create policy "ngsl_frequency_select_all" on public.ngsl_frequency
  for select to authenticated using (true);

revoke all on public.ngsl_frequency from authenticated, anon;
grant select on public.ngsl_frequency to authenticated;

commit;
